%% MECHANISM_DECOMPOSITION_MULTISEED
% Multi-seed mechanism-decomposition experiment for the Chapter 2 ABM.
%
% PURPOSE
% Test whether the role of each mechanism is stable across different
% synthetic initial networks.
%
% This script DOES NOT modify the benchmark model.
% It uses:
%
%   robustness/run_model_mechanism.m
%
% -------------------------------------------------------------------------
% DESIGN
% -------------------------------------------------------------------------
%
% 30 initial-network seeds
%
% For every seed:
%
%   M0 Minimal adaptation
%       -> baseline only
%
%   M1 + Softmax choice
%       -> baseline only
%
%   M2 + Switching costs
%       -> baseline only
%
%   M3 + Recovery
%       -> baseline only
%
%   M4 + Regulation
%       -> baseline + coordinated regulation
%
%   M5 + Policy timing
%       -> all five policy-timing scenarios
%
% Total:
%
%   30 * (4 + 2 + 5)
%   = 330 simulations
%
% -------------------------------------------------------------------------
% MEMORY NOTE
% -------------------------------------------------------------------------
%
% Full A/W histories are NOT retained across replications.
% Only compact final statistics are stored.
%
% -------------------------------------------------------------------------
% OUTPUT
% -------------------------------------------------------------------------
%
% results/robustness/mechanism_decomposition_multiseed/
%
%   mechanism_multiseed_raw.csv
%   mechanism_multiseed_summary.csv
%   mechanism_increment_effects.csv
%   regulation_effect_paired.csv
%   timing_winner_counts.csv
%   mechanism_multiseed_results.mat


clear;
clc;


%% ------------------------------------------------------------------------
% Paths
%% ------------------------------------------------------------------------

scriptDir = ...
    fileparts( ...
        mfilename("fullpath"));

projectRoot = ...
    fileparts(scriptDir);

addpath( ...
    fullfile( ...
        projectRoot, ...
        "src"));

addpath( ...
    fullfile( ...
        projectRoot, ...
        "scenarios"));

addpath(scriptDir);

dataDir = ...
    fullfile( ...
        projectRoot, ...
        "data");

outputDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "mechanism_decomposition_multiseed");

if ~exist(outputDir, "dir")

    mkdir(outputDir);

end


%% ------------------------------------------------------------------------
% Load model inputs
%% ------------------------------------------------------------------------

data = ...
    load_model_data(dataDir);


%% ------------------------------------------------------------------------
% Benchmark parameters
%% ------------------------------------------------------------------------

params.T = 20;

params.p = 0.50;

params.eL = 0.10;

params.eG = 0.20;

params.beta = 4.0;

params.recoveryHorizon = 5;


%% ------------------------------------------------------------------------
% Replication design
%% ------------------------------------------------------------------------
%
% 30 networks are sufficient here because this is a mechanism-
% decomposition exercise rather than the main Monte Carlo robustness test.

nReplications = 30;

seeds = ...
    (1:nReplications)';


%% ------------------------------------------------------------------------
% Scenarios
%% ------------------------------------------------------------------------

scenarioBaseline = ...
    baseline( ...
        data, ...
        params.T);

scenarioCoordinated = ...
    coordinated( ...
        data, ...
        params.T);

scenarioTiming = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};


%% ------------------------------------------------------------------------
% Mechanism definitions
%% ------------------------------------------------------------------------

M0 = struct( ...
    "id", ...
    "M0_minimal", ...
    "label", ...
    "M0 Minimal adaptation", ...
    "useSoftmax", ...
    false, ...
    "useSwitchingCosts", ...
    false, ...
    "useRecovery", ...
    false, ...
    "useRegulation", ...
    false);


M1 = struct( ...
    "id", ...
    "M1_choice", ...
    "label", ...
    "M1 + Softmax choice", ...
    "useSoftmax", ...
    true, ...
    "useSwitchingCosts", ...
    false, ...
    "useRecovery", ...
    false, ...
    "useRegulation", ...
    false);


M2 = struct( ...
    "id", ...
    "M2_frictions", ...
    "label", ...
    "M2 + Switching costs", ...
    "useSoftmax", ...
    true, ...
    "useSwitchingCosts", ...
    true, ...
    "useRecovery", ...
    false, ...
    "useRegulation", ...
    false);


M3 = struct( ...
    "id", ...
    "M3_recovery", ...
    "label", ...
    "M3 + Recovery", ...
    "useSoftmax", ...
    true, ...
    "useSwitchingCosts", ...
    true, ...
    "useRecovery", ...
    true, ...
    "useRegulation", ...
    false);


M4 = struct( ...
    "id", ...
    "M4_regulation", ...
    "label", ...
    "M4 + Regulation", ...
    "useSoftmax", ...
    true, ...
    "useSwitchingCosts", ...
    true, ...
    "useRecovery", ...
    true, ...
    "useRegulation", ...
    true);


M5 = struct( ...
    "id", ...
    "M5_timing", ...
    "label", ...
    "M5 + Policy timing", ...
    "useSoftmax", ...
    true, ...
    "useSwitchingCosts", ...
    true, ...
    "useRecovery", ...
    true, ...
    "useRegulation", ...
    true);


baselineMechanisms = {
    M0
    M1
    M2
    M3
};


%% ------------------------------------------------------------------------
% Preallocate output
%% ------------------------------------------------------------------------

runsPerReplication = ...
    4 + 2 + 5;

nRows = ...
    nReplications ...
    * runsPerReplication;


replication = ...
    zeros(nRows,1);

seed = ...
    zeros(nRows,1);


mechanismID = ...
    strings(nRows,1);

mechanismLabel = ...
    strings(nRows,1);


scenarioID = ...
    strings(nRows,1);

scenarioName = ...
    strings(nRows,1);


finalFitness = ...
    zeros(nRows,1);

finalRisk = ...
    zeros(nRows,1);

finalTrade = ...
    zeros(nRows,1);

finalRecoveringLinks = ...
    zeros(nRows,1);


totalSwitches = ...
    zeros(nRows,1);

localSwitches = ...
    zeros(nRows,1);

globalSwitches = ...
    zeros(nRows,1);


row = 0;


%% ------------------------------------------------------------------------
% Start experiment
%% ------------------------------------------------------------------------

fprintf("\n");

fprintf( ...
    "============================================================\n");

fprintf( ...
    " Multi-seed Mechanism Decomposition\n");

fprintf( ...
    " %d initial networks x %d runs = %d simulations\n", ...
    nReplications, ...
    runsPerReplication, ...
    nRows);

fprintf( ...
    "============================================================\n\n");


%% ------------------------------------------------------------------------
% Replication loop
%% ------------------------------------------------------------------------

for r = 1:nReplications


    fprintf( ...
        "Replication %d/%d\n", ...
        r, ...
        nReplications);


    %% ---------------------------------------------------------------
    % Generate one initial network
    %% ---------------------------------------------------------------

    rng( ...
        seeds(r), ...
        "twister");


    initialState = ...
        initialize_network(data);


    %% Common random numbers
    %
    % All mechanism/scenario comparisons for this network start from the
    % same post-initialization random-number state.

    simulationRNG = ...
        rng;


    %% ---------------------------------------------------------------
    % M0-M3
    %
    % Baseline only
    %% ---------------------------------------------------------------

    for m = 1:numel(baselineMechanisms)


        mechanism = ...
            baselineMechanisms{m};


        rng(simulationRNG);


        result = ...
            run_model_mechanism( ...
                initialState, ...
                data, ...
                params, ...
                scenarioBaseline, ...
                mechanism);


        row = ...
            row + 1;


        replication(row) = ...
            r;

        seed(row) = ...
            seeds(r);


        mechanismID(row) = ...
            string( ...
                mechanism.id);

        mechanismLabel(row) = ...
            string( ...
                mechanism.label);


        scenarioID(row) = ...
            string( ...
                scenarioBaseline.id);

        scenarioName(row) = ...
            string( ...
                scenarioBaseline.name);


        finalFitness(row) = ...
            result.F(end);

        finalRisk(row) = ...
            result.R(end);

        finalTrade(row) = ...
            result.totalTrade(end);

        finalRecoveringLinks(row) = ...
            result.numRecoveringLinks(end);


        totalSwitches(row) = ...
            sum( ...
                result.numSwitches);

        localSwitches(row) = ...
            sum( ...
                result.numLocalSwitches);

        globalSwitches(row) = ...
            sum( ...
                result.numGlobalSwitches);


        %% Free full history immediately

        clear result;


    end


    %% ---------------------------------------------------------------
    % M4
    %
    % Regulation without timing comparison:
    %
    % Baseline versus coordinated regulation
    %% ---------------------------------------------------------------

    m4Scenarios = {
        scenarioBaseline
        scenarioCoordinated
    };


    for s = 1:numel(m4Scenarios)


        scenario = ...
            m4Scenarios{s};


        rng(simulationRNG);


        result = ...
            run_model_mechanism( ...
                initialState, ...
                data, ...
                params, ...
                scenario, ...
                M4);


        row = ...
            row + 1;


        replication(row) = ...
            r;

        seed(row) = ...
            seeds(r);


        mechanismID(row) = ...
            string( ...
                M4.id);

        mechanismLabel(row) = ...
            string( ...
                M4.label);


        scenarioID(row) = ...
            string( ...
                scenario.id);

        scenarioName(row) = ...
            string( ...
                scenario.name);


        finalFitness(row) = ...
            result.F(end);

        finalRisk(row) = ...
            result.R(end);

        finalTrade(row) = ...
            result.totalTrade(end);

        finalRecoveringLinks(row) = ...
            result.numRecoveringLinks(end);


        totalSwitches(row) = ...
            sum( ...
                result.numSwitches);

        localSwitches(row) = ...
            sum( ...
                result.numLocalSwitches);

        globalSwitches(row) = ...
            sum( ...
                result.numGlobalSwitches);


        clear result;


    end


    %% ---------------------------------------------------------------
    % M5
    %
    % Complete policy-timing comparison
    %% ---------------------------------------------------------------

    for s = 1:numel(scenarioTiming)


        scenario = ...
            scenarioTiming{s};


        rng(simulationRNG);


        result = ...
            run_model_mechanism( ...
                initialState, ...
                data, ...
                params, ...
                scenario, ...
                M5);


        row = ...
            row + 1;


        replication(row) = ...
            r;

        seed(row) = ...
            seeds(r);


        mechanismID(row) = ...
            string( ...
                M5.id);

        mechanismLabel(row) = ...
            string( ...
                M5.label);


        scenarioID(row) = ...
            string( ...
                scenario.id);

        scenarioName(row) = ...
            string( ...
                scenario.name);


        finalFitness(row) = ...
            result.F(end);

        finalRisk(row) = ...
            result.R(end);

        finalTrade(row) = ...
            result.totalTrade(end);

        finalRecoveringLinks(row) = ...
            result.numRecoveringLinks(end);


        totalSwitches(row) = ...
            sum( ...
                result.numSwitches);

        localSwitches(row) = ...
            sum( ...
                result.numLocalSwitches);

        globalSwitches(row) = ...
            sum( ...
                result.numGlobalSwitches);


        clear result;


    end


    %% ---------------------------------------------------------------
    % Free replication-specific state
    %% ---------------------------------------------------------------

    clear initialState simulationRNG;


end


assert( ...
    row == nRows, ...
    "Unexpected number of output rows.");


%% ------------------------------------------------------------------------
% Raw results table
%% ------------------------------------------------------------------------

rawTable = ...
    table( ...
        replication, ...
        seed, ...
        mechanismID, ...
        mechanismLabel, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches);


rawFile = ...
    fullfile( ...
        outputDir, ...
        "mechanism_multiseed_raw.csv");


writetable( ...
    rawTable, ...
    rawFile);


%% ------------------------------------------------------------------------
% Aggregate summary
%% ------------------------------------------------------------------------

[ ...
    groupID, ...
    groupMechanismID, ...
    groupMechanismLabel, ...
    groupScenarioID, ...
    groupScenarioName ...
] = ...
    findgroups( ...
        rawTable.mechanismID, ...
        rawTable.mechanismLabel, ...
        rawTable.scenarioID, ...
        rawTable.scenarioName);


n = ...
    splitapply( ...
        @numel, ...
        rawTable.finalRisk, ...
        groupID);


meanFinalRisk = ...
    splitapply( ...
        @mean, ...
        rawTable.finalRisk, ...
        groupID);

sdFinalRisk = ...
    splitapply( ...
        @std, ...
        rawTable.finalRisk, ...
        groupID);


meanFinalFitness = ...
    splitapply( ...
        @mean, ...
        rawTable.finalFitness, ...
        groupID);

sdFinalFitness = ...
    splitapply( ...
        @std, ...
        rawTable.finalFitness, ...
        groupID);


meanFinalTrade = ...
    splitapply( ...
        @mean, ...
        rawTable.finalTrade, ...
        groupID);

sdFinalTrade = ...
    splitapply( ...
        @std, ...
        rawTable.finalTrade, ...
        groupID);


meanTotalSwitches = ...
    splitapply( ...
        @mean, ...
        rawTable.totalSwitches, ...
        groupID);

sdTotalSwitches = ...
    splitapply( ...
        @std, ...
        rawTable.totalSwitches, ...
        groupID);


meanLocalSwitches = ...
    splitapply( ...
        @mean, ...
        rawTable.localSwitches, ...
        groupID);


meanGlobalSwitches = ...
    splitapply( ...
        @mean, ...
        rawTable.globalSwitches, ...
        groupID);


summaryTable = ...
    table( ...
        groupMechanismID, ...
        groupMechanismLabel, ...
        groupScenarioID, ...
        groupScenarioName, ...
        n, ...
        meanFinalRisk, ...
        sdFinalRisk, ...
        meanFinalFitness, ...
        sdFinalFitness, ...
        meanFinalTrade, ...
        sdFinalTrade, ...
        meanTotalSwitches, ...
        sdTotalSwitches, ...
        meanLocalSwitches, ...
        meanGlobalSwitches);


summaryFile = ...
    fullfile( ...
        outputDir, ...
        "mechanism_multiseed_summary.csv");


writetable( ...
    summaryTable, ...
    summaryFile);


%% ------------------------------------------------------------------------
% Paired incremental mechanism effects
%
% M1 - M0
% M2 - M1
% M3 - M2
%% ------------------------------------------------------------------------

incrementLabels = [
    "M1 - M0"
    "M2 - M1"
    "M3 - M2"
];


incrementFrom = [
    "M0_minimal"
    "M1_choice"
    "M2_frictions"
];


incrementTo = [
    "M1_choice"
    "M2_frictions"
    "M3_recovery"
];


nIncrements = ...
    numel( ...
        incrementLabels);


meanDeltaRisk = ...
    zeros(nIncrements,1);

sdDeltaRisk = ...
    zeros(nIncrements,1);


meanDeltaFitness = ...
    zeros(nIncrements,1);

sdDeltaFitness = ...
    zeros(nIncrements,1);


meanDeltaTrade = ...
    zeros(nIncrements,1);

sdDeltaTrade = ...
    zeros(nIncrements,1);


meanDeltaSwitches = ...
    zeros(nIncrements,1);

sdDeltaSwitches = ...
    zeros(nIncrements,1);


for q = 1:nIncrements


    fromMask = ...
        rawTable.mechanismID == incrementFrom(q) ...
        & rawTable.scenarioID == "baseline";


    toMask = ...
        rawTable.mechanismID == incrementTo(q) ...
        & rawTable.scenarioID == "baseline";


    fromRows = ...
        rawTable( ...
            fromMask, ...
            :);


    toRows = ...
        rawTable( ...
            toMask, ...
            :);


    fromRows = ...
        sortrows( ...
            fromRows, ...
            "replication");


    toRows = ...
        sortrows( ...
            toRows, ...
            "replication");


    assert( ...
        isequal( ...
            fromRows.replication, ...
            toRows.replication), ...
        "Paired mechanism rows do not align.");


    dRisk = ...
        toRows.finalRisk ...
        - fromRows.finalRisk;


    dFitness = ...
        toRows.finalFitness ...
        - fromRows.finalFitness;


    dTrade = ...
        toRows.finalTrade ...
        - fromRows.finalTrade;


    dSwitches = ...
        toRows.totalSwitches ...
        - fromRows.totalSwitches;


    meanDeltaRisk(q) = ...
        mean(dRisk);

    sdDeltaRisk(q) = ...
        std(dRisk);


    meanDeltaFitness(q) = ...
        mean(dFitness);

    sdDeltaFitness(q) = ...
        std(dFitness);


    meanDeltaTrade(q) = ...
        mean(dTrade);

    sdDeltaTrade(q) = ...
        std(dTrade);


    meanDeltaSwitches(q) = ...
        mean(dSwitches);

    sdDeltaSwitches(q) = ...
        std(dSwitches);


end


incrementTable = ...
    table( ...
        incrementLabels, ...
        meanDeltaRisk, ...
        sdDeltaRisk, ...
        meanDeltaFitness, ...
        sdDeltaFitness, ...
        meanDeltaTrade, ...
        sdDeltaTrade, ...
        meanDeltaSwitches, ...
        sdDeltaSwitches);


incrementFile = ...
    fullfile( ...
        outputDir, ...
        "mechanism_increment_effects.csv");


writetable( ...
    incrementTable, ...
    incrementFile);


%% ------------------------------------------------------------------------
% Paired regulation effect at M4
%% ------------------------------------------------------------------------

m4Base = ...
    rawTable( ...
        rawTable.mechanismID == "M4_regulation" ...
        & rawTable.scenarioID == "baseline", ...
        :);


m4Policy = ...
    rawTable( ...
        rawTable.mechanismID == "M4_regulation" ...
        & rawTable.scenarioID == "coordinated", ...
        :);


m4Base = ...
    sortrows( ...
        m4Base, ...
        "replication");


m4Policy = ...
    sortrows( ...
        m4Policy, ...
        "replication");


assert( ...
    isequal( ...
        m4Base.replication, ...
        m4Policy.replication), ...
    "M4 baseline and coordinated rows do not align.");


regulationEffectTable = ...
    table( ...
        m4Base.replication, ...
        m4Base.seed, ...
        m4Policy.finalRisk ...
            - m4Base.finalRisk, ...
        m4Policy.finalFitness ...
            - m4Base.finalFitness, ...
        m4Policy.finalTrade ...
            - m4Base.finalTrade, ...
        m4Policy.totalSwitches ...
            - m4Base.totalSwitches, ...
        'VariableNames', { ...
            'replication', ...
            'seed', ...
            'deltaFinalRisk', ...
            'deltaFinalFitness', ...
            'deltaFinalTrade', ...
            'deltaTotalSwitches'});


regulationEffectFile = ...
    fullfile( ...
        outputDir, ...
        "regulation_effect_paired.csv");


writetable( ...
    regulationEffectTable, ...
    regulationEffectFile);


%% ------------------------------------------------------------------------
% M5 timing winner counts
%% ------------------------------------------------------------------------

timingIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];


winnerCount = ...
    zeros( ...
        numel(timingIDs), ...
        1);


for r = 1:nReplications


    repMask = ...
        rawTable.replication == r ...
        & rawTable.mechanismID == "M5_timing" ...
        & ismember( ...
            rawTable.scenarioID, ...
            timingIDs);


    repRows = ...
        rawTable( ...
            repMask, ...
            :);


    minRisk = ...
        min( ...
            repRows.finalRisk);


    winners = ...
        repRows.scenarioID( ...
            abs( ...
                repRows.finalRisk ...
                - minRisk) ...
            < 1e-12);


    for w = 1:numel(winners)


        idx = ...
            find( ...
                timingIDs == winners(w), ...
                1);


        winnerCount(idx) = ...
            winnerCount(idx) + 1;


    end


end


winnerTable = ...
    table( ...
        timingIDs, ...
        winnerCount, ...
        winnerCount ...
            ./ nReplications, ...
        'VariableNames', { ...
            'scenarioID', ...
            'winnerCount', ...
            'winnerShare'});


winnerFile = ...
    fullfile( ...
        outputDir, ...
        "timing_winner_counts.csv");


writetable( ...
    winnerTable, ...
    winnerFile);


%% ------------------------------------------------------------------------
% Save compact MAT output
%% ------------------------------------------------------------------------

matFile = ...
    fullfile( ...
        outputDir, ...
        "mechanism_multiseed_results.mat");


save( ...
    matFile, ...
    "rawTable", ...
    "summaryTable", ...
    "incrementTable", ...
    "regulationEffectTable", ...
    "winnerTable", ...
    "params", ...
    "nReplications", ...
    "seeds", ...
    "M0", ...
    "M1", ...
    "M2", ...
    "M3", ...
    "M4", ...
    "M5", ...
    "-v7.3");


%% ------------------------------------------------------------------------
% Console output
%% ------------------------------------------------------------------------

fprintf("\n");

fprintf( ...
    "============================================================\n");

fprintf( ...
    " Multi-seed mechanism decomposition complete\n");

fprintf( ...
    "============================================================\n\n");


fprintf( ...
    "Aggregate mechanism/scenario results:\n\n");

disp(summaryTable);


fprintf( ...
    "\nIncremental mechanism effects:\n\n");

disp(incrementTable);


fprintf( ...
    "\nM4 coordinated-regulation effect ");
fprintf( ...
    "(paired mean across networks):\n");


fprintf( ...
    "  Mean delta final risk:     %+10.4f\n", ...
    mean( ...
        regulationEffectTable.deltaFinalRisk));


fprintf( ...
    "  Mean delta final fitness:  %+10.4f\n", ...
    mean( ...
        regulationEffectTable.deltaFinalFitness));


fprintf( ...
    "  Mean delta final trade:    %+10.4f\n", ...
    mean( ...
        regulationEffectTable.deltaFinalTrade));


fprintf( ...
    "  Mean delta switches:       %+10.2f\n\n", ...
    mean( ...
        regulationEffectTable.deltaTotalSwitches));


fprintf( ...
    "M5 timing winner counts:\n\n");

disp(winnerTable);


fprintf( ...
    "\nFiles saved to:\n  %s\n", ...
    outputDir);