%% ENVIRONMENTAL RISK DECOMPOSITION
% Decomposes policy-induced changes in embodied deforestation risk into:
%
%   1. aggregate trade-volume effect
%   2. trade-weighted deforestation-risk composition effect
%
% This is an ANALYSIS of completed simulation results.
% It does NOT rerun the ABM and does NOT change model behavior.
%
% -------------------------------------------------------------------------
% MODEL IDENTITY
% -------------------------------------------------------------------------
%
% Environmental risk:
%
%   R_t = sum_{i,c,j} W_ij^{c,t} * delta_ic
%
% Define total trade:
%
%   Q_t = sum_{i,c,j} W_ij^{c,t}
%
% and trade-weighted average deforestation intensity:
%
%   deltaBar_t = R_t / Q_t
%
% Therefore:
%
%   R_t = Q_t * deltaBar_t
%
% For policy scenario s relative to baseline B:
%
%   Delta R = R_s - R_B
%
% The exact symmetric decomposition is:
%
%   Delta R_volume
%       = ((deltaBar_s + deltaBar_B)/2)
%         * (Q_s - Q_B)
%
%   Delta R_composition
%       = ((Q_s + Q_B)/2)
%         * (deltaBar_s - deltaBar_B)
%
% so that:
%
%   Delta R
%       = Delta R_volume
%         + Delta R_composition
%
% up to floating-point precision.
%
% -------------------------------------------------------------------------
% INTERPRETATION
% -------------------------------------------------------------------------
%
% Volume effect:
%   environmental-risk change caused by higher/lower aggregate realized
%   trade volume.
%
% Composition effect:
%   environmental-risk change caused by the remaining trade being weighted
%   toward exporter-commodity combinations with higher/lower deforestation
%   intensity.
%
% IMPORTANT:
% Because delta_ic depends on exporter i and commodity c, not importer j,
% pure destination rerouting does not mechanically change environmental
% risk. Composition changes occur through differential changes in volumes
% across exporter-commodity combinations.

clear;
clc;

%% ------------------------------------------------------------------------
% Paths
%% ------------------------------------------------------------------------

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

resultsFile = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "networks_recovery", ...
        "robustness_networks_recovery_results.mat");

analysisDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "analysis", ...
        "environmental_decomposition");

if ~exist(analysisDir, "dir")
    mkdir(analysisDir);
end

%% ------------------------------------------------------------------------
% Load completed joint robustness results
%% ------------------------------------------------------------------------

load( ...
    resultsFile, ...
    "summaryTable", ...
    "riskPath", ...
    "tradePath", ...
    "recoveryHorizons", ...
    "scenarioList");

%% ------------------------------------------------------------------------
% Basic dimensions
%% ------------------------------------------------------------------------

nRows = ...
    height(summaryTable);

Tplus1 = ...
    size(riskPath,2);

T = ...
    Tplus1 - 1;

nReplications = ...
    max(summaryTable.replication);

nHorizons = ...
    numel(recoveryHorizons);

%% ------------------------------------------------------------------------
% Calculate trade-weighted average deforestation intensity
%% ------------------------------------------------------------------------
%
% deltaBar = R / Q

deltaBarPath = ...
    nan(size(riskPath));

validTrade = ...
    tradePath > 0;

deltaBarPath(validTrade) = ...
    riskPath(validTrade) ./ tradePath(validTrade);

%% ------------------------------------------------------------------------
% Preallocate decomposition output
%% ------------------------------------------------------------------------

maxRows = ...
    nReplications ...
    * nHorizons ...
    * numel(scenarioList) ...
    * Tplus1;

replicationOut = ...
    zeros(maxRows,1);

recoveryHorizonOut = ...
    zeros(maxRows,1);

scenarioIDOut = ...
    strings(maxRows,1);

scenarioNameOut = ...
    strings(maxRows,1);

timeOut = ...
    zeros(maxRows,1);

riskPolicyOut = ...
    zeros(maxRows,1);

riskBaselineOut = ...
    zeros(maxRows,1);

tradePolicyOut = ...
    zeros(maxRows,1);

tradeBaselineOut = ...
    zeros(maxRows,1);

deltaBarPolicyOut = ...
    zeros(maxRows,1);

deltaBarBaselineOut = ...
    zeros(maxRows,1);

deltaRiskOut = ...
    zeros(maxRows,1);

volumeEffectOut = ...
    zeros(maxRows,1);

compositionEffectOut = ...
    zeros(maxRows,1);

decompositionResidualOut = ...
    zeros(maxRows,1);

volumeShareOut = ...
    nan(maxRows,1);

compositionShareOut = ...
    nan(maxRows,1);

rowOut = 0;

%% ------------------------------------------------------------------------
% Decompose each scenario against paired baseline
%% ------------------------------------------------------------------------

for r = 1:nReplications

    for h = 1:nHorizons

        H = ...
            recoveryHorizons(h);

        rowsRH = ...
            summaryTable.replication == r ...
            & summaryTable.recoveryHorizon == H;

        baselineRow = ...
            find( ...
                rowsRH ...
                & summaryTable.scenarioID == "baseline");

        assert( ...
            numel(baselineRow) == 1, ...
            "Expected exactly one baseline row for each replication/H.");

        for s = 1:numel(scenarioList)

            scenario = ...
                scenarioList{s};

            scenarioRow = ...
                find( ...
                    rowsRH ...
                    & summaryTable.scenarioID == scenario.id);

            assert( ...
                numel(scenarioRow) == 1, ...
                "Expected exactly one scenario row for each replication/H.");

            for tt = 1:Tplus1

                rowOut = ...
                    rowOut + 1;

                %% Current policy and baseline values

                R_s = ...
                    riskPath(scenarioRow,tt);

                R_b = ...
                    riskPath(baselineRow,tt);

                Q_s = ...
                    tradePath(scenarioRow,tt);

                Q_b = ...
                    tradePath(baselineRow,tt);

                d_s = ...
                    deltaBarPath(scenarioRow,tt);

                d_b = ...
                    deltaBarPath(baselineRow,tt);

                %% Total policy effect

                deltaR = ...
                    R_s - R_b;

                %% Symmetric volume effect

                volumeEffect = ...
                    ((d_s + d_b) ./ 2) ...
                    .* (Q_s - Q_b);

                %% Symmetric composition effect

                compositionEffect = ...
                    ((Q_s + Q_b) ./ 2) ...
                    .* (d_s - d_b);

                %% Exact-identity diagnostic

                residual = ...
                    deltaR ...
                    - volumeEffect ...
                    - compositionEffect;

                %% Shares of total environmental-risk change
                %
                % For small Delta R, shares are left as NaN because ratios
                % would be unstable and economically uninformative.

                volumeShare = NaN;

                compositionShare = NaN;

                if abs(deltaR) > 1e-10

                    volumeShare = ...
                        volumeEffect ./ deltaR;

                    compositionShare = ...
                        compositionEffect ./ deltaR;

                end

                %% Store

                replicationOut(rowOut) = ...
                    r;

                recoveryHorizonOut(rowOut) = ...
                    H;

                scenarioIDOut(rowOut) = ...
                    scenario.id;

                scenarioNameOut(rowOut) = ...
                    scenario.name;

                % t = 0 corresponds to initial network.
                timeOut(rowOut) = ...
                    tt - 1;

                riskPolicyOut(rowOut) = ...
                    R_s;

                riskBaselineOut(rowOut) = ...
                    R_b;

                tradePolicyOut(rowOut) = ...
                    Q_s;

                tradeBaselineOut(rowOut) = ...
                    Q_b;

                deltaBarPolicyOut(rowOut) = ...
                    d_s;

                deltaBarBaselineOut(rowOut) = ...
                    d_b;

                deltaRiskOut(rowOut) = ...
                    deltaR;

                volumeEffectOut(rowOut) = ...
                    volumeEffect;

                compositionEffectOut(rowOut) = ...
                    compositionEffect;

                decompositionResidualOut(rowOut) = ...
                    residual;

                volumeShareOut(rowOut) = ...
                    volumeShare;

                compositionShareOut(rowOut) = ...
                    compositionShare;

            end

        end

    end

end

%% ------------------------------------------------------------------------
% Remove unused preallocation
%% ------------------------------------------------------------------------

replicationOut = ...
    replicationOut(1:rowOut);

recoveryHorizonOut = ...
    recoveryHorizonOut(1:rowOut);

scenarioIDOut = ...
    scenarioIDOut(1:rowOut);

scenarioNameOut = ...
    scenarioNameOut(1:rowOut);

timeOut = ...
    timeOut(1:rowOut);

riskPolicyOut = ...
    riskPolicyOut(1:rowOut);

riskBaselineOut = ...
    riskBaselineOut(1:rowOut);

tradePolicyOut = ...
    tradePolicyOut(1:rowOut);

tradeBaselineOut = ...
    tradeBaselineOut(1:rowOut);

deltaBarPolicyOut = ...
    deltaBarPolicyOut(1:rowOut);

deltaBarBaselineOut = ...
    deltaBarBaselineOut(1:rowOut);

deltaRiskOut = ...
    deltaRiskOut(1:rowOut);

volumeEffectOut = ...
    volumeEffectOut(1:rowOut);

compositionEffectOut = ...
    compositionEffectOut(1:rowOut);

decompositionResidualOut = ...
    decompositionResidualOut(1:rowOut);

volumeShareOut = ...
    volumeShareOut(1:rowOut);

compositionShareOut = ...
    compositionShareOut(1:rowOut);

%% ------------------------------------------------------------------------
% Full decomposition table
%% ------------------------------------------------------------------------

decompositionTable = ...
    table( ...
        replicationOut, ...
        recoveryHorizonOut, ...
        scenarioIDOut, ...
        scenarioNameOut, ...
        timeOut, ...
        riskPolicyOut, ...
        riskBaselineOut, ...
        tradePolicyOut, ...
        tradeBaselineOut, ...
        deltaBarPolicyOut, ...
        deltaBarBaselineOut, ...
        deltaRiskOut, ...
        volumeEffectOut, ...
        compositionEffectOut, ...
        decompositionResidualOut, ...
        volumeShareOut, ...
        compositionShareOut, ...
        'VariableNames', { ...
            'replication', ...
            'recovery_horizon', ...
            'scenario_id', ...
            'scenario_name', ...
            'time', ...
            'risk_policy', ...
            'risk_baseline', ...
            'trade_policy', ...
            'trade_baseline', ...
            'weighted_deforestation_intensity_policy', ...
            'weighted_deforestation_intensity_baseline', ...
            'delta_risk', ...
            'volume_effect', ...
            'composition_effect', ...
            'decomposition_residual', ...
            'volume_share_of_delta_risk', ...
            'composition_share_of_delta_risk' ...
        });

%% ------------------------------------------------------------------------
% Check decomposition identity
%% ------------------------------------------------------------------------

maxResidual = ...
    max(abs(decompositionTable.decomposition_residual));

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Environmental Risk Decomposition\n");
fprintf("============================================================\n\n");

fprintf( ...
    "Maximum absolute decomposition residual: %.12g\n", ...
    maxResidual);

if maxResidual > 1e-8

    warning( ...
        "Decomposition residual is larger than expected.");

end

%% ------------------------------------------------------------------------
% Final-period decomposition
%% ------------------------------------------------------------------------

finalRows = ...
    decompositionTable.time == T;

finalTable = ...
    decompositionTable(finalRows,:);

%% Exclude baseline from policy-effect summaries
%
% Baseline is identically zero relative to itself.

finalPolicyTable = ...
    finalTable( ...
        finalTable.scenario_id ~= "baseline", ...
        :);

%% ------------------------------------------------------------------------
% Aggregate final-period effects
%% ------------------------------------------------------------------------

aggregateFinal = ...
    groupsummary( ...
        finalPolicyTable, ...
        ["recovery_horizon", ...
         "scenario_id", ...
         "scenario_name"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "delta_risk", ...
            "volume_effect", ...
            "composition_effect", ...
            "volume_share_of_delta_risk", ...
            "composition_share_of_delta_risk", ...
            "trade_policy", ...
            "trade_baseline", ...
            "weighted_deforestation_intensity_policy", ...
            "weighted_deforestation_intensity_baseline" ...
        ]);

%% ------------------------------------------------------------------------
% Mean trajectories by H, scenario, and time
%% ------------------------------------------------------------------------

trajectorySummary = ...
    groupsummary( ...
        decompositionTable( ...
            decompositionTable.scenario_id ~= "baseline", ...
            :), ...
        ["recovery_horizon", ...
         "scenario_id", ...
         "scenario_name", ...
         "time"], ...
        ["mean","std"], ...
        [ ...
            "delta_risk", ...
            "volume_effect", ...
            "composition_effect", ...
            "volume_share_of_delta_risk", ...
            "composition_share_of_delta_risk" ...
        ]);

%% ------------------------------------------------------------------------
% Direction diagnostics
%% ------------------------------------------------------------------------
%
% Count how frequently each component contributes to a reduction in risk.
%
% Negative component:
%   contributes to lower environmental risk relative to baseline.

negativeVolume = ...
    finalPolicyTable.volume_effect < 0;

negativeComposition = ...
    finalPolicyTable.composition_effect < 0;

directionTable = ...
    table( ...
        finalPolicyTable.recovery_horizon, ...
        finalPolicyTable.scenario_id, ...
        finalPolicyTable.scenario_name, ...
        negativeVolume, ...
        negativeComposition, ...
        'VariableNames', { ...
            'recovery_horizon', ...
            'scenario_id', ...
            'scenario_name', ...
            'volume_effect_reduces_risk', ...
            'composition_effect_reduces_risk' ...
        });

directionSummary = ...
    groupsummary( ...
        directionTable, ...
        ["recovery_horizon", ...
         "scenario_id", ...
         "scenario_name"], ...
        "sum", ...
        [ ...
            "volume_effect_reduces_risk", ...
            "composition_effect_reduces_risk" ...
        ]);

%% ------------------------------------------------------------------------
% Save outputs
%% ------------------------------------------------------------------------

save( ...
    fullfile( ...
        analysisDir, ...
        "environmental_risk_decomposition.mat"), ...
    "decompositionTable", ...
    "finalTable", ...
    "finalPolicyTable", ...
    "aggregateFinal", ...
    "trajectorySummary", ...
    "directionTable", ...
    "directionSummary", ...
    "maxResidual", ...
    "-v7.3");

writetable( ...
    decompositionTable, ...
    fullfile( ...
        analysisDir, ...
        "environmental_risk_decomposition_full.csv"));

writetable( ...
    aggregateFinal, ...
    fullfile( ...
        analysisDir, ...
        "environmental_risk_decomposition_final_aggregate.csv"));

writetable( ...
    trajectorySummary, ...
    fullfile( ...
        analysisDir, ...
        "environmental_risk_decomposition_trajectories.csv"));

writetable( ...
    directionSummary, ...
    fullfile( ...
        analysisDir, ...
        "environmental_risk_decomposition_direction.csv"));

%% ------------------------------------------------------------------------
% Display final aggregate
%% ------------------------------------------------------------------------

fprintf("\nFinal-period decomposition across 100 networks:\n\n");

disp(aggregateFinal);

fprintf("\nDirection diagnostics:\n\n");

disp(directionSummary);

fprintf( ...
    "\nResults saved in:\n%s\n", ...
    analysisDir);