%% PLACEBO / FALSIFICATION TEST:
% DEFORESTATION-INTENSITY PERMUTATION
%
% Tests whether environmental policy-timing outcomes depend on the
% empirical placement of deforestation risk across countries.
%
% IMPORTANT:
%
% delta_ic does NOT enter partner choice.
%
% Therefore permuting delta should NOT change:
%
%   - network structure
%   - partner switching
%   - trade-volume paths
%
% It changes only environmental-risk measurement.
%
% -------------------------------------------------------------------------
% PLACEBO DESIGN
% -------------------------------------------------------------------------
%
% For each replication:
%
%   1. generate one synthetic initial network
%   2. permute delta values independently within each commodity layer
%   3. run all five scenarios with the same permuted delta
%
% This preserves the empirical distribution of deforestation intensity
% within every commodity while destroying its country assignment.
%
% Design:
%
%   100 network realizations / delta permutations
%   x 5 scenarios
%
%   = 500 simulations
%
% Baseline behavioral specification:
%
%   p = 0.50
%   eL = 0.10
%   eG = 0.20
%   beta = 4
%   recovery horizon = 5 years

clear;
clc;

%% Paths

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath(fullfile(projectRoot, "src"));
addpath(fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "placebo_deforestation");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% Load original data

dataOriginal = ...
    load_model_data(dataDir);

%% Parameters

params.T = 20;

params.p = 0.50;

params.eL = 0.10;

params.eG = 0.20;

params.beta = 4.0;

params.recoveryHorizon = 5;

%% Monte Carlo / permutation design

nReplications = 100;

seeds = ...
    (1:nReplications)';

%% Scenarios

scenarioList = {
    baseline(dataOriginal, params.T)
    early_mover(dataOriginal, params.T)
    sequential(dataOriginal, params.T)
    coordinated(dataOriginal, params.T)
    delayed_coordination(dataOriginal, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% Storage

nRows = ...
    nReplications ...
    * nScenarios;

replication = zeros(nRows,1);
seed = zeros(nRows,1);

scenarioID = strings(nRows,1);
scenarioName = strings(nRows,1);

finalFitness = zeros(nRows,1);

finalRiskPermuted = zeros(nRows,1);
finalRiskOriginal = zeros(nRows,1);

totalTrade = zeros(nRows,1);

totalSwitches = zeros(nRows,1);

riskDifferencePermutation = zeros(nRows,1);

riskPathPermuted = ...
    zeros(nRows, params.T + 1);

riskPathOriginal = ...
    zeros(nRows, params.T + 1);

tradePath = ...
    zeros(nRows, params.T + 1);

switchPath = ...
    zeros(nRows, params.T);

row = 0;

%% Run placebo

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Deforestation-Intensity Permutation Placebo\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    %% ---------------------------------------------------------------
    % Initial network
    %% ---------------------------------------------------------------

    rng(seeds(r), "twister");

    initialStateOriginal = ...
        initialize_network(dataOriginal);

    simulationRNG = ...
        rng;

    %% ---------------------------------------------------------------
    % Permute delta within commodity layers
    %% ---------------------------------------------------------------

    dataPermuted = ...
        dataOriginal;

    deltaPermuted = ...
        dataOriginal.delta;

    [N,C] = ...
        size(deltaPermuted);

    %% Separate deterministic permutation seed
    %
    % Keeps permutation reproducible without affecting simulation RNG.

    rng(100000 + seeds(r), "twister");

    for c = 1:C

        permutation = ...
            randperm(N);

        deltaPermuted(:,c) = ...
            dataOriginal.delta(permutation,c);

    end

    dataPermuted.delta = ...
        deltaPermuted;

    %% Same initial topology and weights, but alternative environmental data

    initialStatePermuted = ...
        initialStateOriginal;

    initialStatePermuted.delta = ...
        deltaPermuted;

    fprintf("Replication %d/%d\n", r, nReplications);

    %% ---------------------------------------------------------------
    % Run scenarios
    %% ---------------------------------------------------------------

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        %% ---------------------------
        % Original delta run
        %% ---------------------------

        rng(simulationRNG);

        resultOriginal = ...
            run_model( ...
                initialStateOriginal, ...
                dataOriginal, ...
                params, ...
                scenario);

        %% ---------------------------
        % Permuted delta run
        %% ---------------------------

        rng(simulationRNG);

        resultPermuted = ...
            run_model( ...
                initialStatePermuted, ...
                dataPermuted, ...
                params, ...
                scenario);

        %% -----------------------------------------------------------
        % Internal falsification check
        %% -----------------------------------------------------------
        %
        % delta should not influence behavioral dynamics.

        assert( ...
            max(abs( ...
                resultOriginal.totalTrade ...
                - resultPermuted.totalTrade)) < 1e-10, ...
            "Permutation changed total-trade dynamics.");

        assert( ...
            isequal( ...
                resultOriginal.numSwitches, ...
                resultPermuted.numSwitches), ...
            "Permutation changed switching dynamics.");

        %% Store

        row = ...
            row + 1;

        replication(row) = r;
        seed(row) = seeds(r);

        scenarioID(row) = ...
            scenario.id;

        scenarioName(row) = ...
            scenario.name;

        finalFitness(row) = ...
            resultPermuted.F(end);

        finalRiskOriginal(row) = ...
            resultOriginal.R(end);

        finalRiskPermuted(row) = ...
            resultPermuted.R(end);

        totalTrade(row) = ...
            resultPermuted.totalTrade(end);

        totalSwitches(row) = ...
            sum(resultPermuted.numSwitches);

        riskDifferencePermutation(row) = ...
            resultPermuted.R(end) ...
            - resultOriginal.R(end);

        riskPathOriginal(row,:) = ...
            resultOriginal.R(:)';

        riskPathPermuted(row,:) = ...
            resultPermuted.R(:)';

        tradePath(row,:) = ...
            resultPermuted.totalTrade(:)';

        switchPath(row,:) = ...
            resultPermuted.numSwitches(:)';

    end

end

%% Checkpoint

save( ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_checkpoint.mat"), ...
    "replication", ...
    "seed", ...
    "scenarioID", ...
    "scenarioName", ...
    "finalFitness", ...
    "finalRiskOriginal", ...
    "finalRiskPermuted", ...
    "totalTrade", ...
    "totalSwitches", ...
    "riskDifferencePermutation", ...
    "riskPathOriginal", ...
    "riskPathPermuted", ...
    "tradePath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "scenarioList", ...
    "-v7.3");

fprintf("\nCheckpoint saved.\n");

%% Summary

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRiskOriginal, ...
        finalRiskPermuted, ...
        riskDifferencePermutation, ...
        totalTrade, ...
        totalSwitches, ...
        'VariableNames', { ...
            'replication', ...
            'seed', ...
            'scenario_id', ...
            'scenario_name', ...
            'final_fitness', ...
            'final_risk_original', ...
            'final_risk_permuted', ...
            'delta_risk_permutation_minus_original', ...
            'final_trade', ...
            'total_switches'});

%% Aggregate placebo effects

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["scenario_id","scenario_name"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "final_risk_original", ...
            "final_risk_permuted", ...
            "delta_risk_permutation_minus_original" ...
        ]);

%% Policy effects relative to baseline under permuted delta

differenceRows = [];

for r = 1:nReplications

    rowsR = ...
        summaryTable.replication == r;

    baselineRow = ...
        rowsR ...
        & summaryTable.scenario_id == "baseline";

    baselineRiskPermuted = ...
        summaryTable.final_risk_permuted(baselineRow);

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        scenarioRow = ...
            rowsR ...
            & summaryTable.scenario_id == scenario.id;

        newRow = ...
            table( ...
                r, ...
                seeds(r), ...
                string(scenario.id), ...
                summaryTable.final_risk_permuted(scenarioRow) ...
                    - baselineRiskPermuted, ...
                'VariableNames', { ...
                    'replication', ...
                    'seed', ...
                    'scenario_id', ...
                    'delta_final_risk_vs_permuted_baseline'});

        differenceRows = ...
            [differenceRows; newRow]; %#ok<AGROW>

    end

end

differenceAggregate = ...
    groupsummary( ...
        differenceRows, ...
        "scenario_id", ...
        ["mean","std","median","min","max"], ...
        "delta_final_risk_vs_permuted_baseline");

%% Lowest-risk policy under permuted delta

winnerReplication = ...
    zeros(nReplications,1);

winnerScenario = ...
    strings(nReplications,1);

winnerRisk = ...
    zeros(nReplications,1);

for r = 1:nReplications

    rowsR = ...
        summaryTable.replication == r ...
        & summaryTable.scenario_id ~= "baseline";

    policyRows = ...
        find(rowsR);

    risks = ...
        summaryTable.final_risk_permuted(policyRows);

    [minRisk, idx] = ...
        min(risks);

    selectedRow = ...
        policyRows(idx);

    winnerReplication(r) = r;

    winnerScenario(r) = ...
        summaryTable.scenario_id(selectedRow);

    winnerRisk(r) = ...
        minRisk;

end

winnerTable = ...
    table( ...
        winnerReplication, ...
        winnerScenario, ...
        winnerRisk, ...
        'VariableNames', { ...
            'replication', ...
            'lowest_risk_scenario', ...
            'lowest_final_risk'});

winnerFrequency = ...
    groupcounts( ...
        winnerTable, ...
        "lowest_risk_scenario");

%% Save

save( ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "differenceAggregate", ...
    "winnerTable", ...
    "winnerFrequency", ...
    "riskPathOriginal", ...
    "riskPathPermuted", ...
    "tradePath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "scenarioList", ...
    "-v7.3");

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_summary.csv"));

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_aggregate.csv"));

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_differences.csv"));

writetable( ...
    differenceAggregate, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_difference_aggregate.csv"));

writetable( ...
    winnerTable, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_winners.csv"));

writetable( ...
    winnerFrequency, ...
    fullfile( ...
        resultsDir, ...
        "placebo_deforestation_permutation_winner_frequency.csv"));

fprintf("\nPlacebo permutation test complete.\n\n");

disp(aggregateTable);
disp(differenceAggregate);
disp(winnerFrequency);

fprintf("\nResults saved in:\n%s\n", resultsDir);