%% ROBUSTNESS: INITIAL NETWORKS x REGULATORY PENALTY
% Joint robustness exercise for the final Chapter 2 model.
%
% This script tests whether the policy-timing result survives variation in:
%
%   1. synthetic initial network structure
%   2. strength of the regulatory penalty p
%
% Design:
%
%   100 initial networks
%   x 3 regulatory-penalty values
%   x 5 policy scenarios
%
%   = 1500 complete simulations
%
% Regulatory penalty values:
%
%   p = 0.25   weaker regulatory penalty
%   p = 0.50   baseline
%   p = 0.75   stronger regulatory penalty
%
% -------------------------------------------------------------------------
% FINAL MODEL LOGIC HELD FIXED
% -------------------------------------------------------------------------
%
% One model period = one year.
%
% Partner score:
%
%   S = phi - d + w - p*rho
%
% New replacement relationship:
%
%   W_new,0 = W_old * wHat_new
%
% Conditional on survival, replacement relationships recover linearly
% toward W_old over five years.
%
% Each dropped relationship is replaced one-for-one.
%
% No eta parameter is used.
%
% -------------------------------------------------------------------------
% COMMON RANDOM NUMBERS
% -------------------------------------------------------------------------
%
% Within each replication:
%
%   - the same initialized network is used for all p values
%   - all policy scenarios within each p value start from the same RNG state
%
% This allows paired policy comparisons within each network realization.

clear;
clc;

%% ------------------------------------------------------------------------
% Paths
%% ------------------------------------------------------------------------

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath( ...
    fullfile(projectRoot, "src"));

addpath( ...
    fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "networks_policy_penalty");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% ------------------------------------------------------------------------
% Load inputs
%% ------------------------------------------------------------------------

data = ...
    load_model_data(dataDir);

%% ------------------------------------------------------------------------
% Locked baseline behavioral parameters
%% ------------------------------------------------------------------------

params.T = 20;

params.eL = 0.10;

params.eG = 0.20;

params.beta = 4.0;

params.recoveryHorizon = 5;

assert( ...
    params.eG > params.eL, ...
    "Global switching cost eG must exceed local switching cost eL.");

%% ------------------------------------------------------------------------
% Regulatory-penalty robustness values
%% ------------------------------------------------------------------------

pValues = ...
    [0.25 0.50 0.75];

nP = ...
    numel(pValues);

%% ------------------------------------------------------------------------
% Monte Carlo design
%% ------------------------------------------------------------------------

nReplications = 100;

seeds = ...
    (1:nReplications)';

%% ------------------------------------------------------------------------
% Policy scenarios
%% ------------------------------------------------------------------------

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% ------------------------------------------------------------------------
% Output dimensions
%% ------------------------------------------------------------------------

nRows = ...
    nReplications ...
    * nP ...
    * nScenarios;

replication = ...
    zeros(nRows,1);

seed = ...
    zeros(nRows,1);

policyPenalty = ...
    zeros(nRows,1);

scenarioID = ...
    strings(nRows,1);

scenarioName = ...
    strings(nRows,1);

finalFitness = ...
    zeros(nRows,1);

finalRisk = ...
    zeros(nRows,1);

finalTrade = ...
    zeros(nRows,1);

finalRecoveringLinks = ...
    zeros(nRows,1);

totalSwitches = ...
    zeros(nRows,1);

localSwitches = ...
    zeros(nRows,1);

globalSwitches = ...
    zeros(nRows,1);

%% ------------------------------------------------------------------------
% Full time paths
%% ------------------------------------------------------------------------

fitnessPath = ...
    zeros(nRows, params.T + 1);

riskPath = ...
    zeros(nRows, params.T + 1);

tradePath = ...
    zeros(nRows, params.T + 1);

recoveringLinksPath = ...
    zeros(nRows, params.T + 1);

switchPath = ...
    zeros(nRows, params.T);

row = 0;

%% ------------------------------------------------------------------------
% Run experiment
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Joint Initial-Network x Regulatory-Penalty Robustness\n");
fprintf(" 100 networks x 3 p-values x 5 scenarios = 1500 runs\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    %% ---------------------------------------------------------------
    % Generate one synthetic initial network
    %% ---------------------------------------------------------------

    rng(seeds(r), "twister");

    initialState = ...
        initialize_network(data);

    %% Save RNG state after initialization

    simulationRNG = ...
        rng;

    fprintf( ...
        "Replication %d/%d\n", ...
        r, ...
        nReplications);

    %% ---------------------------------------------------------------
    % Regulatory-penalty loop
    %% ---------------------------------------------------------------

    for pp = 1:nP

        params.p = ...
            pValues(pp);

        %% -----------------------------------------------------------
        % Policy-scenario loop
        %% -----------------------------------------------------------

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            %% Common random numbers

            rng(simulationRNG);

            %% Run model

            result = ...
                run_model( ...
                    initialState, ...
                    data, ...
                    params, ...
                    scenario);

            row = ...
                row + 1;

            %% -------------------------------------------------------
            % Identification
            %% -------------------------------------------------------

            replication(row) = ...
                r;

            seed(row) = ...
                seeds(r);

            policyPenalty(row) = ...
                params.p;

            scenarioID(row) = ...
                scenario.id;

            scenarioName(row) = ...
                scenario.name;

            %% -------------------------------------------------------
            % Final outcomes
            %% -------------------------------------------------------

            finalFitness(row) = ...
                result.F(end);

            finalRisk(row) = ...
                result.R(end);

            finalTrade(row) = ...
                result.totalTrade(end);

            finalRecoveringLinks(row) = ...
                result.numRecoveringLinks(end);

            %% -------------------------------------------------------
            % Switching outcomes
            %% -------------------------------------------------------

            totalSwitches(row) = ...
                sum(result.numSwitches);

            localSwitches(row) = ...
                sum(result.numLocalSwitches);

            globalSwitches(row) = ...
                sum(result.numGlobalSwitches);

            %% -------------------------------------------------------
            % Time paths
            %% -------------------------------------------------------

            fitnessPath(row,:) = ...
                result.F(:)';

            riskPath(row,:) = ...
                result.R(:)';

            tradePath(row,:) = ...
                result.totalTrade(:)';

            recoveringLinksPath(row,:) = ...
                result.numRecoveringLinks(:)';

            switchPath(row,:) = ...
                result.numSwitches(:)';

        end

    end

end

%% ------------------------------------------------------------------------
% CHECKPOINT SAVE
%% ------------------------------------------------------------------------
%
% Save raw simulation outputs before post-processing so a failure in
% summary construction does not require rerunning all 1500 simulations.

checkpointFile = ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_checkpoint.mat");

save( ...
    checkpointFile, ...
    "replication", ...
    "seed", ...
    "policyPenalty", ...
    "scenarioID", ...
    "scenarioName", ...
    "finalFitness", ...
    "finalRisk", ...
    "finalTrade", ...
    "finalRecoveringLinks", ...
    "totalSwitches", ...
    "localSwitches", ...
    "globalSwitches", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "pValues", ...
    "scenarioList", ...
    "-v7.3");

fprintf("\nCheckpoint saved before post-processing.\n");

%% ------------------------------------------------------------------------
% Main results table
%% ------------------------------------------------------------------------

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        policyPenalty, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches);

%% ------------------------------------------------------------------------
% Aggregate by p and scenario
%% ------------------------------------------------------------------------

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["policyPenalty", ...
         "scenarioID", ...
         "scenarioName"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "finalFitness", ...
            "finalRisk", ...
            "finalTrade", ...
            "finalRecoveringLinks", ...
            "totalSwitches", ...
            "localSwitches", ...
            "globalSwitches" ...
        ]);

%% ------------------------------------------------------------------------
% Paired differences relative to baseline
%% ------------------------------------------------------------------------

differenceRows = [];

for r = 1:nReplications

    for pp = 1:nP

        pValue = ...
            pValues(pp);

        rowsRP = ...
            summaryTable.replication == r ...
            & summaryTable.policyPenalty == pValue;

        baselineRow = ...
            rowsRP ...
            & summaryTable.scenarioID == "baseline";

        baselineFitness = ...
            summaryTable.finalFitness(baselineRow);

        baselineRisk = ...
            summaryTable.finalRisk(baselineRow);

        baselineTrade = ...
            summaryTable.finalTrade(baselineRow);

        baselineRecovering = ...
            summaryTable.finalRecoveringLinks(baselineRow);

        baselineSwitches = ...
            summaryTable.totalSwitches(baselineRow);

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            scenarioRow = ...
                rowsRP ...
                & summaryTable.scenarioID == scenario.id;

            newRow = ...
                table( ...
                    r, ...
                    seeds(r), ...
                    pValue, ...
                    string(scenario.id), ...
                    string(scenario.name), ...
                    summaryTable.finalFitness(scenarioRow) ...
                        - baselineFitness, ...
                    summaryTable.finalRisk(scenarioRow) ...
                        - baselineRisk, ...
                    summaryTable.finalTrade(scenarioRow) ...
                        - baselineTrade, ...
                    summaryTable.finalRecoveringLinks(scenarioRow) ...
                        - baselineRecovering, ...
                    summaryTable.totalSwitches(scenarioRow) ...
                        - baselineSwitches, ...
                    'VariableNames', { ...
                        'replication', ...
                        'seed', ...
                        'policy_penalty', ...
                        'scenario_id', ...
                        'scenario_name', ...
                        'delta_final_fitness_vs_baseline', ...
                        'delta_final_risk_vs_baseline', ...
                        'delta_final_trade_vs_baseline', ...
                        'delta_recovering_links_vs_baseline', ...
                        'delta_total_switches_vs_baseline' ...
                    });

            differenceRows = ...
                [differenceRows; newRow]; %#ok<AGROW>

        end

    end

end

%% ------------------------------------------------------------------------
% Pairwise policy comparisons
%% ------------------------------------------------------------------------

policyIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];

pairwiseRows = [];

for r = 1:nReplications

    for pp = 1:nP

        pValue = ...
            pValues(pp);

        rowsRP = ...
            summaryTable.replication == r ...
            & summaryTable.policyPenalty == pValue;

        for a = 1:numel(policyIDs)

            for b = (a+1):numel(policyIDs)

                idA = ...
                    policyIDs(a);

                idB = ...
                    policyIDs(b);

                rowA = ...
                    rowsRP ...
                    & summaryTable.scenarioID == idA;

                rowB = ...
                    rowsRP ...
                    & summaryTable.scenarioID == idB;

                newPair = ...
                    table( ...
                        r, ...
                        seeds(r), ...
                        pValue, ...
                        idA, ...
                        idB, ...
                        summaryTable.finalFitness(rowA) ...
                            - summaryTable.finalFitness(rowB), ...
                        summaryTable.finalRisk(rowA) ...
                            - summaryTable.finalRisk(rowB), ...
                        summaryTable.finalTrade(rowA) ...
                            - summaryTable.finalTrade(rowB), ...
                        summaryTable.totalSwitches(rowA) ...
                            - summaryTable.totalSwitches(rowB), ...
                        'VariableNames', { ...
                            'replication', ...
                            'seed', ...
                            'policy_penalty', ...
                            'scenario_A', ...
                            'scenario_B', ...
                            'delta_final_fitness_A_minus_B', ...
                            'delta_final_risk_A_minus_B', ...
                            'delta_final_trade_A_minus_B', ...
                            'delta_switches_A_minus_B' ...
                        });

                pairwiseRows = ...
                    [pairwiseRows; newPair]; %#ok<AGROW>

            end

        end

    end

end

%% ------------------------------------------------------------------------
% Identify lowest-risk policy within each network and p
%% ------------------------------------------------------------------------

winnerReplication = ...
    zeros(nReplications * nP,1);

winnerPenalty = ...
    zeros(nReplications * nP,1);

winnerScenario = ...
    strings(nReplications * nP,1);

winnerRisk = ...
    zeros(nReplications * nP,1);

winnerRow = 0;

for r = 1:nReplications

    for pp = 1:nP

        pValue = ...
            pValues(pp);

        rowsRP = ...
            summaryTable.replication == r ...
            & summaryTable.policyPenalty == pValue ...
            & summaryTable.scenarioID ~= "baseline";

        policyRows = ...
            find(rowsRP);

        risks = ...
            summaryTable.finalRisk(policyRows);

        [minRisk, idx] = ...
            min(risks);

        selectedRow = ...
            policyRows(idx);

        winnerRow = ...
            winnerRow + 1;

        winnerReplication(winnerRow) = ...
            r;

        winnerPenalty(winnerRow) = ...
            pValue;

        winnerScenario(winnerRow) = ...
            summaryTable.scenarioID(selectedRow);

        winnerRisk(winnerRow) = ...
            minRisk;

    end

end

winnerTable = ...
    table( ...
        winnerReplication, ...
        winnerPenalty, ...
        winnerScenario, ...
        winnerRisk, ...
        'VariableNames', { ...
            'replication', ...
            'policy_penalty', ...
            'lowest_risk_scenario', ...
            'lowest_final_risk'});

%% ------------------------------------------------------------------------
% Winner frequencies
%% ------------------------------------------------------------------------

winnerFrequency = ...
    groupcounts( ...
        winnerTable, ...
        ["policy_penalty", ...
         "lowest_risk_scenario"]);

%% ------------------------------------------------------------------------
% Save outputs
%% ------------------------------------------------------------------------

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "pairwiseRows", ...
    "winnerTable", ...
    "winnerFrequency", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "pValues", ...
    "scenarioList", ...
    "-v7.3");

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_summary.csv"));

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_aggregate.csv"));

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_differences.csv"));

writetable( ...
    pairwiseRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_pairwise.csv"));

writetable( ...
    winnerTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_winners.csv"));

writetable( ...
    winnerFrequency, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_policy_penalty_winner_frequency.csv"));

%% ------------------------------------------------------------------------
% Display aggregate output
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("Policy-penalty robustness complete.\n\n");

disp(aggregateTable);

fprintf("\nLowest-risk scenario frequencies:\n\n");

disp(winnerFrequency);

fprintf( ...
    "\nResults saved in:\n%s\n", ...
    resultsDir);