%% ROBUSTNESS: INITIAL NETWORKS x SWITCHING COSTS
%
% Tests whether the policy-timing result survives variation in:
%
%   1. synthetic initial network structure
%   2. local/global switching costs
%
% Design:
%
%   100 initial networks
%   x 3 switching-cost regimes
%   x 5 policy scenarios
%
%   = 1500 simulations
%
% Cost regimes:
%
%   Low friction:
%       eL = 0.05
%       eG = 0.10
%
%   Baseline:
%       eL = 0.10
%       eG = 0.20
%
%   High friction:
%       eL = 0.20
%       eG = 0.40
%
% The relationship eG > eL is preserved in every specification.
%
% All other model elements remain fixed.

clear;
clc;

%% Paths

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath(fullfile(projectRoot, "src"));
addpath(fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "networks_switching_costs");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% Load data

data = ...
    load_model_data(dataDir);

%% Fixed model parameters

params.T = 20;

params.p = 0.50;

params.beta = 4.0;

params.recoveryHorizon = 5;

%% Switching-cost regimes

costRegimes = [
    0.05  0.10
    0.10  0.20
    0.20  0.40
];

costLabels = [
    "low"
    "baseline"
    "high"
];

nRegimes = ...
    size(costRegimes,1);

%% Monte Carlo

nReplications = 100;

seeds = ...
    (1:nReplications)';

%% Scenarios

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% Storage

nRows = ...
    nReplications ...
    * nRegimes ...
    * nScenarios;

replication = zeros(nRows,1);
seed = zeros(nRows,1);

costRegime = strings(nRows,1);

eLColumn = zeros(nRows,1);
eGColumn = zeros(nRows,1);

scenarioID = strings(nRows,1);
scenarioName = strings(nRows,1);

finalFitness = zeros(nRows,1);
finalRisk = zeros(nRows,1);
finalTrade = zeros(nRows,1);
finalRecoveringLinks = zeros(nRows,1);

totalSwitches = zeros(nRows,1);
localSwitches = zeros(nRows,1);
globalSwitches = zeros(nRows,1);

fitnessPath = zeros(nRows, params.T + 1);
riskPath = zeros(nRows, params.T + 1);
tradePath = zeros(nRows, params.T + 1);
recoveringLinksPath = zeros(nRows, params.T + 1);
switchPath = zeros(nRows, params.T);

row = 0;

%% Run experiment

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Initial-Network x Switching-Cost Robustness\n");
fprintf(" 100 networks x 3 cost regimes x 5 scenarios\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    rng(seeds(r), "twister");

    initialState = ...
        initialize_network(data);

    simulationRNG = ...
        rng;

    fprintf( ...
        "Replication %d/%d\n", ...
        r, ...
        nReplications);

    for cc = 1:nRegimes

        params.eL = ...
            costRegimes(cc,1);

        params.eG = ...
            costRegimes(cc,2);

        assert( ...
            params.eG > params.eL, ...
            "eG must exceed eL.");

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            %% Common random numbers

            rng(simulationRNG);

            result = ...
                run_model( ...
                    initialState, ...
                    data, ...
                    params, ...
                    scenario);

            row = ...
                row + 1;

            replication(row) = r;
            seed(row) = seeds(r);

            costRegime(row) = ...
                costLabels(cc);

            eLColumn(row) = ...
                params.eL;

            eGColumn(row) = ...
                params.eG;

            scenarioID(row) = ...
                scenario.id;

            scenarioName(row) = ...
                scenario.name;

            finalFitness(row) = ...
                result.F(end);

            finalRisk(row) = ...
                result.R(end);

            finalTrade(row) = ...
                result.totalTrade(end);

            finalRecoveringLinks(row) = ...
                result.numRecoveringLinks(end);

            totalSwitches(row) = ...
                sum(result.numSwitches);

            localSwitches(row) = ...
                sum(result.numLocalSwitches);

            globalSwitches(row) = ...
                sum(result.numGlobalSwitches);

            fitnessPath(row,:) = ...
                result.F(:)';

            riskPath(row,:) = ...
                result.R(:)';

            tradePath(row,:) = ...
                result.totalTrade(:)';

            recoveringLinksPath(row,:) = ...
                result.numRecoveringLinks(:)';

            switchPath(row,:) = ...
                result.numSwitches(:)';

        end

    end

end

%% Checkpoint

checkpointFile = ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_checkpoint.mat");

save( ...
    checkpointFile, ...
    "replication", ...
    "seed", ...
    "costRegime", ...
    "eLColumn", ...
    "eGColumn", ...
    "scenarioID", ...
    "scenarioName", ...
    "finalFitness", ...
    "finalRisk", ...
    "finalTrade", ...
    "finalRecoveringLinks", ...
    "totalSwitches", ...
    "localSwitches", ...
    "globalSwitches", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "costRegimes", ...
    "costLabels", ...
    "scenarioList", ...
    "-v7.3");

fprintf("\nCheckpoint saved.\n");

%% Summary table

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        costRegime, ...
        eLColumn, ...
        eGColumn, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches, ...
        'VariableNames', { ...
            'replication', ...
            'seed', ...
            'cost_regime', ...
            'eL', ...
            'eG', ...
            'scenario_id', ...
            'scenario_name', ...
            'final_fitness', ...
            'final_risk', ...
            'final_trade', ...
            'final_recovering_links', ...
            'total_switches', ...
            'local_switches', ...
            'global_switches'});

%% Aggregate

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["cost_regime","eL","eG","scenario_id","scenario_name"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "final_fitness", ...
            "final_risk", ...
            "final_trade", ...
            "final_recovering_links", ...
            "total_switches", ...
            "local_switches", ...
            "global_switches" ...
        ]);

%% Differences versus baseline

differenceRows = [];

for r = 1:nReplications

    for cc = 1:nRegimes

        regime = ...
            costLabels(cc);

        rowsRC = ...
            summaryTable.replication == r ...
            & summaryTable.cost_regime == regime;

        baselineRow = ...
            rowsRC ...
            & summaryTable.scenario_id == "baseline";

        baselineFitness = ...
            summaryTable.final_fitness(baselineRow);

        baselineRisk = ...
            summaryTable.final_risk(baselineRow);

        baselineTrade = ...
            summaryTable.final_trade(baselineRow);

        baselineSwitches = ...
            summaryTable.total_switches(baselineRow);

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            scenarioRow = ...
                rowsRC ...
                & summaryTable.scenario_id == scenario.id;

            newRow = ...
                table( ...
                    r, ...
                    seeds(r), ...
                    regime, ...
                    costRegimes(cc,1), ...
                    costRegimes(cc,2), ...
                    string(scenario.id), ...
                    summaryTable.final_fitness(scenarioRow) ...
                        - baselineFitness, ...
                    summaryTable.final_risk(scenarioRow) ...
                        - baselineRisk, ...
                    summaryTable.final_trade(scenarioRow) ...
                        - baselineTrade, ...
                    summaryTable.total_switches(scenarioRow) ...
                        - baselineSwitches, ...
                    'VariableNames', { ...
                        'replication', ...
                        'seed', ...
                        'cost_regime', ...
                        'eL', ...
                        'eG', ...
                        'scenario_id', ...
                        'delta_final_fitness_vs_baseline', ...
                        'delta_final_risk_vs_baseline', ...
                        'delta_final_trade_vs_baseline', ...
                        'delta_total_switches_vs_baseline'});

            differenceRows = ...
                [differenceRows; newRow]; %#ok<AGROW>

        end

    end

end

%% Winner frequencies

policyIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];

winnerReplication = zeros(nReplications*nRegimes,1);
winnerRegime = strings(nReplications*nRegimes,1);
winnerScenario = strings(nReplications*nRegimes,1);
winnerRisk = zeros(nReplications*nRegimes,1);

winnerRow = 0;

for r = 1:nReplications

    for cc = 1:nRegimes

        regime = ...
            costLabels(cc);

        rowsRC = ...
            summaryTable.replication == r ...
            & summaryTable.cost_regime == regime ...
            & summaryTable.scenario_id ~= "baseline";

        policyRows = ...
            find(rowsRC);

        risks = ...
            summaryTable.final_risk(policyRows);

        [minRisk, idx] = ...
            min(risks);

        selectedRow = ...
            policyRows(idx);

        winnerRow = ...
            winnerRow + 1;

        winnerReplication(winnerRow) = r;
        winnerRegime(winnerRow) = regime;

        winnerScenario(winnerRow) = ...
            summaryTable.scenario_id(selectedRow);

        winnerRisk(winnerRow) = ...
            minRisk;

    end

end

winnerTable = ...
    table( ...
        winnerReplication, ...
        winnerRegime, ...
        winnerScenario, ...
        winnerRisk, ...
        'VariableNames', { ...
            'replication', ...
            'cost_regime', ...
            'lowest_risk_scenario', ...
            'lowest_final_risk'});

winnerFrequency = ...
    groupcounts( ...
        winnerTable, ...
        ["cost_regime","lowest_risk_scenario"]);

%% Save

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "winnerTable", ...
    "winnerFrequency", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "costRegimes", ...
    "costLabels", ...
    "scenarioList", ...
    "-v7.3");

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_summary.csv"));

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_aggregate.csv"));

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_differences.csv"));

writetable( ...
    winnerTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_winners.csv"));

writetable( ...
    winnerFrequency, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_switching_costs_winner_frequency.csv"));

fprintf("\nSwitching-cost robustness complete.\n\n");
disp(aggregateTable);
disp(winnerFrequency);

fprintf("\nResults saved in:\n%s\n", resultsDir);