%% ROBUSTNESS: INITIAL NETWORK / MONTE CARLO
% Tests whether the policy-timing result persists across independently
% generated synthetic initial trade networks.
%
% FINAL MODEL LOGIC:
%
%   - one model period = one year
%   - no eta parameter
%   - replacement links initially absorb:
%
%       W_new,0 = W_old * wHat_new
%
%   - if the replacement relationship survives, trade volume recovers
%     linearly toward W_old over five years
%
%   - every dropped relationship is replaced one-for-one
%
% IMPORTANT:
% This robustness exercise changes ONLY the synthetic initial network.
%
% Behavioral parameters, policy timing, recovery logic, empirical inputs,
% and model structure remain unchanged.
%
% COMMON RANDOM NUMBERS:
% Within each Monte Carlo replication, all five scenarios begin from:
%
%   1. the exact same initialized network
%   2. the exact same stochastic state
%
% Therefore scenario comparisons are paired within each replication.

clear;
clc;

%% ------------------------------------------------------------------------
% Paths
%% ------------------------------------------------------------------------

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath( ...
    fullfile(projectRoot, "src"));

addpath( ...
    fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "monte_carlo");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% ------------------------------------------------------------------------
% Load empirical / semi-empirical inputs
%% ------------------------------------------------------------------------

data = ...
    load_model_data(dataDir);

%% ------------------------------------------------------------------------
% Locked baseline model specification
%% ------------------------------------------------------------------------

% Simulation horizon:
% one period = one year

params.T = 20;

% Regulatory penalty

params.p = 0.50;

% Local switching cost

params.eL = 0.10;

% Global switching cost

params.eG = 0.20;

assert( ...
    params.eG > params.eL, ...
    "Global switching cost eG must exceed local switching cost eL.");

% Softmax choice sensitivity

params.beta = 4.0;

% Trade-volume recovery horizon
%
% Replacement relationships recover linearly toward their pre-switch
% volume over five surviving years.

params.recoveryHorizon = 5;

%% ------------------------------------------------------------------------
% Monte Carlo design
%% ------------------------------------------------------------------------
%
% 100 independently initialized networks.
%
% This is a simulation-design choice, not a behavioral parameter.

nReplications = 100;

seeds = ...
    (1:nReplications)';

%% ------------------------------------------------------------------------
% Define policy scenarios
%% ------------------------------------------------------------------------

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% ------------------------------------------------------------------------
% Preallocate compact outputs
%% ------------------------------------------------------------------------

nRows = ...
    nReplications * nScenarios;

replication = ...
    zeros(nRows,1);

seed = ...
    zeros(nRows,1);

scenarioID = ...
    strings(nRows,1);

scenarioName = ...
    strings(nRows,1);

finalFitness = ...
    zeros(nRows,1);

finalRisk = ...
    zeros(nRows,1);

finalTrade = ...
    zeros(nRows,1);

finalRecoveringLinks = ...
    zeros(nRows,1);

totalSwitches = ...
    zeros(nRows,1);

localSwitches = ...
    zeros(nRows,1);

globalSwitches = ...
    zeros(nRows,1);

%% ------------------------------------------------------------------------
% Store full time paths
%% ------------------------------------------------------------------------

fitnessPath = ...
    zeros(nRows, params.T + 1);

riskPath = ...
    zeros(nRows, params.T + 1);

tradePath = ...
    zeros(nRows, params.T + 1);

recoveringLinksPath = ...
    zeros(nRows, params.T + 1);

switchPath = ...
    zeros(nRows, params.T);

localSwitchPath = ...
    zeros(nRows, params.T);

globalSwitchPath = ...
    zeros(nRows, params.T);

row = 0;

%% ------------------------------------------------------------------------
% Monte Carlo loop
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Monte Carlo Initial-Network Robustness\n");
fprintf(" Final five-year recovery specification\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    %% ---------------------------------------------------------------
    % Generate independent synthetic initial network
    %% ---------------------------------------------------------------

    rng(seeds(r), "twister");

    initialState = ...
        initialize_network(data);

    %% ---------------------------------------------------------------
    % Save stochastic state AFTER initialization
    %% ---------------------------------------------------------------
    %
    % Every scenario in replication r will begin from this same RNG state.

    simulationRNG = ...
        rng;

    fprintf( ...
        "Replication %d/%d\n", ...
        r, ...
        nReplications);

    %% ---------------------------------------------------------------
    % Run all five scenarios
    %% ---------------------------------------------------------------

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        %% Common random numbers

        rng(simulationRNG);

        %% Run model

        result = ...
            run_model( ...
                initialState, ...
                data, ...
                params, ...
                scenario);

        row = ...
            row + 1;

        %% -----------------------------------------------------------
        % Identification
        %% -----------------------------------------------------------

        replication(row) = ...
            r;

        seed(row) = ...
            seeds(r);

        scenarioID(row) = ...
            scenario.id;

        scenarioName(row) = ...
            scenario.name;

        %% -----------------------------------------------------------
        % Final outcomes
        %% -----------------------------------------------------------

        finalFitness(row) = ...
            result.F(end);

        finalRisk(row) = ...
            result.R(end);

        finalTrade(row) = ...
            result.totalTrade(end);

        finalRecoveringLinks(row) = ...
            result.numRecoveringLinks(end);

        %% -----------------------------------------------------------
        % Switching totals
        %% -----------------------------------------------------------

        totalSwitches(row) = ...
            sum(result.numSwitches);

        localSwitches(row) = ...
            sum(result.numLocalSwitches);

        globalSwitches(row) = ...
            sum(result.numGlobalSwitches);

        %% -----------------------------------------------------------
        % Complete time paths
        %% -----------------------------------------------------------

        fitnessPath(row,:) = ...
            result.F(:)';

        riskPath(row,:) = ...
            result.R(:)';

        tradePath(row,:) = ...
            result.totalTrade(:)';

        recoveringLinksPath(row,:) = ...
            result.numRecoveringLinks(:)';

        switchPath(row,:) = ...
            result.numSwitches(:)';

        localSwitchPath(row,:) = ...
            result.numLocalSwitches(:)';

        globalSwitchPath(row,:) = ...
            result.numGlobalSwitches(:)';

    end

end

%% ------------------------------------------------------------------------
% Compact Monte Carlo table
%% ------------------------------------------------------------------------

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches);

%% ------------------------------------------------------------------------
% Aggregate results across initial networks
%% ------------------------------------------------------------------------

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["scenarioID","scenarioName"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "finalFitness", ...
            "finalRisk", ...
            "finalTrade", ...
            "finalRecoveringLinks", ...
            "totalSwitches", ...
            "localSwitches", ...
            "globalSwitches" ...
        ]);

%% ------------------------------------------------------------------------
% Paired scenario differences relative to baseline
%% ------------------------------------------------------------------------
%
% Every scenario comparison is paired within the same synthetic network and
% stochastic realization.

differenceRows = [];

for r = 1:nReplications

    rowsR = ...
        summaryTable.replication == r;

    baselineRow = ...
        rowsR ...
        & summaryTable.scenarioID == "baseline";

    baselineFitness = ...
        summaryTable.finalFitness(baselineRow);

    baselineRisk = ...
        summaryTable.finalRisk(baselineRow);

    baselineTrade = ...
        summaryTable.finalTrade(baselineRow);

    baselineRecovering = ...
        summaryTable.finalRecoveringLinks(baselineRow);

    baselineSwitches = ...
        summaryTable.totalSwitches(baselineRow);

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        scenarioRow = ...
            rowsR ...
            & summaryTable.scenarioID == scenario.id;

        newRow = ...
            table( ...
                r, ...
                seeds(r), ...
                string(scenario.id), ...
                string(scenario.name), ...
                summaryTable.finalFitness(scenarioRow) ...
                    - baselineFitness, ...
                summaryTable.finalRisk(scenarioRow) ...
                    - baselineRisk, ...
                summaryTable.finalTrade(scenarioRow) ...
                    - baselineTrade, ...
                summaryTable.finalRecoveringLinks(scenarioRow) ...
                    - baselineRecovering, ...
                summaryTable.totalSwitches(scenarioRow) ...
                    - baselineSwitches, ...
                'VariableNames', { ...
                    'replication', ...
                    'seed', ...
                    'scenario_id', ...
                    'scenario_name', ...
                    'delta_final_fitness_vs_baseline', ...
                    'delta_final_risk_vs_baseline', ...
                    'delta_final_trade_vs_baseline', ...
                    'delta_recovering_links_vs_baseline', ...
                    'delta_total_switches_vs_baseline' ...
                });

        differenceRows = ...
            [differenceRows; newRow]; %#ok<AGROW>

    end

end

%% ------------------------------------------------------------------------
% Pairwise comparisons among policy-timing scenarios
%% ------------------------------------------------------------------------
%
% These are useful for evaluating whether one policy timing consistently
% outperforms another rather than only comparing each policy with baseline.

policyIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];

pairwiseRows = [];

for r = 1:nReplications

    rowsR = ...
        summaryTable.replication == r;

    for a = 1:numel(policyIDs)

        for b = (a+1):numel(policyIDs)

            idA = ...
                policyIDs(a);

            idB = ...
                policyIDs(b);

            rowA = ...
                rowsR ...
                & summaryTable.scenarioID == idA;

            rowB = ...
                rowsR ...
                & summaryTable.scenarioID == idB;

            newPair = ...
                table( ...
                    r, ...
                    seeds(r), ...
                    idA, ...
                    idB, ...
                    summaryTable.finalFitness(rowA) ...
                        - summaryTable.finalFitness(rowB), ...
                    summaryTable.finalRisk(rowA) ...
                        - summaryTable.finalRisk(rowB), ...
                    summaryTable.finalTrade(rowA) ...
                        - summaryTable.finalTrade(rowB), ...
                    summaryTable.totalSwitches(rowA) ...
                        - summaryTable.totalSwitches(rowB), ...
                    'VariableNames', { ...
                        'replication', ...
                        'seed', ...
                        'scenario_A', ...
                        'scenario_B', ...
                        'delta_final_fitness_A_minus_B', ...
                        'delta_final_risk_A_minus_B', ...
                        'delta_final_trade_A_minus_B', ...
                        'delta_switches_A_minus_B' ...
                    });

            pairwiseRows = ...
                [pairwiseRows; newPair]; %#ok<AGROW>

        end

    end

end

%% ------------------------------------------------------------------------
% Save outputs
%% ------------------------------------------------------------------------

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_initial_networks_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "pairwiseRows", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "localSwitchPath", ...
    "globalSwitchPath", ...
    "params", ...
    "seeds", ...
    "scenarioList", ...
    "-v7.3");

%% CSV: all simulation outcomes

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_initial_networks_summary.csv"));

%% CSV: aggregate results

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_initial_networks_aggregate.csv"));

%% CSV: differences versus baseline

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_initial_networks_differences.csv"));

%% CSV: policy-vs-policy comparisons

writetable( ...
    pairwiseRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_initial_networks_pairwise.csv"));

%% ------------------------------------------------------------------------
% Display aggregate results
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("Monte Carlo complete.\n\n");

disp(aggregateTable);

fprintf( ...
    "\nResults saved in:\n%s\n", ...
    resultsDir);