%% ROBUSTNESS: INITIAL NETWORKS x RECOVERY HORIZON
% Joint robustness exercise for the final Chapter 2 model.
%
% This script tests whether the policy-timing result survives variation in:
%
%   1. synthetic initial network structure
%   2. trade-relationship recovery horizon
%
% Design:
%
%   100 initial networks
%   x 3 recovery horizons
%   x 5 policy scenarios
%
%   = 1500 complete simulations
%
% Recovery horizons:
%
%   H = 3 years
%   H = 5 years   [baseline]
%   H = 7 years
%
% -------------------------------------------------------------------------
% FINAL MODEL LOGIC
% -------------------------------------------------------------------------
%
% One model period = one year.
%
% New replacement relationship:
%
%   W_new,0 = W_old * wHat_new
%
% Conditional on survival:
%
%   W(a)
%       = W_new,0
%         + min(a/H,1)
%           * (W_old - W_new,0)
%
% Each dropped relationship is replaced one-for-one.
%
% No eta parameter is used.
%
% -------------------------------------------------------------------------
% COMMON RANDOM NUMBERS
% -------------------------------------------------------------------------
%
% Within each replication:
%
%   - the same initialized network is used for all H values
%   - all policy scenarios within a given H start from the same RNG state
%
% This allows paired policy comparisons within each network realization.

clear;
clc;

%% ------------------------------------------------------------------------
% Paths
%% ------------------------------------------------------------------------

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath( ...
    fullfile(projectRoot, "src"));

addpath( ...
    fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "networks_recovery");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% ------------------------------------------------------------------------
% Load inputs
%% ------------------------------------------------------------------------

data = ...
    load_model_data(dataDir);

%% ------------------------------------------------------------------------
% Locked behavioral parameters
%% ------------------------------------------------------------------------

params.T = 20;

params.p = 0.50;

params.eL = 0.10;

params.eG = 0.20;

params.beta = 4.0;

assert( ...
    params.eG > params.eL, ...
    "Global switching cost eG must exceed local switching cost eL.");

%% ------------------------------------------------------------------------
% Joint robustness design
%% ------------------------------------------------------------------------

nReplications = 100;

seeds = ...
    (1:nReplications)';

recoveryHorizons = ...
    [3 5 7];

nHorizons = ...
    numel(recoveryHorizons);

%% ------------------------------------------------------------------------
% Policy scenarios
%% ------------------------------------------------------------------------

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% ------------------------------------------------------------------------
% Output dimensions
%% ------------------------------------------------------------------------

nRows = ...
    nReplications ...
    * nHorizons ...
    * nScenarios;

replication = ...
    zeros(nRows,1);

seed = ...
    zeros(nRows,1);

recoveryHorizon = ...
    zeros(nRows,1);

scenarioID = ...
    strings(nRows,1);

scenarioName = ...
    strings(nRows,1);

finalFitness = ...
    zeros(nRows,1);

finalRisk = ...
    zeros(nRows,1);

finalTrade = ...
    zeros(nRows,1);

finalRecoveringLinks = ...
    zeros(nRows,1);

totalSwitches = ...
    zeros(nRows,1);

localSwitches = ...
    zeros(nRows,1);

globalSwitches = ...
    zeros(nRows,1);

%% ------------------------------------------------------------------------
% Full time paths
%% ------------------------------------------------------------------------

fitnessPath = ...
    zeros(nRows, params.T + 1);

riskPath = ...
    zeros(nRows, params.T + 1);

tradePath = ...
    zeros(nRows, params.T + 1);

recoveringLinksPath = ...
    zeros(nRows, params.T + 1);

switchPath = ...
    zeros(nRows, params.T);

row = 0;

%% ------------------------------------------------------------------------
% Run experiment
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Joint Initial-Network x Recovery-Horizon Robustness\n");
fprintf(" 100 networks x 3 horizons x 5 scenarios = 1500 runs\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    %% ---------------------------------------------------------------
    % Generate one synthetic initial network
    %% ---------------------------------------------------------------

    rng(seeds(r), "twister");

    initialState = ...
        initialize_network(data);

    %% Save RNG state after initialization
    %
    % This state is reused for every H/scenario comparison in this
    % replication.

    simulationRNG = ...
        rng;

    fprintf( ...
        "Replication %d/%d\n", ...
        r, ...
        nReplications);

    %% ---------------------------------------------------------------
    % Recovery-horizon loop
    %% ---------------------------------------------------------------

    for h = 1:nHorizons

        params.recoveryHorizon = ...
            recoveryHorizons(h);

        %% -----------------------------------------------------------
        % Policy-scenario loop
        %% -----------------------------------------------------------

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            %% Common random numbers
            %
            % Every scenario for this replication and recovery horizon
            % begins from the same stochastic state.

            rng(simulationRNG);

            result = ...
                run_model( ...
                    initialState, ...
                    data, ...
                    params, ...
                    scenario);

            row = ...
                row + 1;

            %% -------------------------------------------------------
            % Identification
            %% -------------------------------------------------------

            replication(row) = ...
                r;

            seed(row) = ...
                seeds(r);

            recoveryHorizon(row) = ...
                params.recoveryHorizon;

            scenarioID(row) = ...
                scenario.id;

            scenarioName(row) = ...
                scenario.name;

            %% -------------------------------------------------------
            % Final outcomes
            %% -------------------------------------------------------

            finalFitness(row) = ...
                result.F(end);

            finalRisk(row) = ...
                result.R(end);

            finalTrade(row) = ...
                result.totalTrade(end);

            finalRecoveringLinks(row) = ...
                result.numRecoveringLinks(end);

            %% -------------------------------------------------------
            % Switching outcomes
            %% -------------------------------------------------------

            totalSwitches(row) = ...
                sum(result.numSwitches);

            localSwitches(row) = ...
                sum(result.numLocalSwitches);

            globalSwitches(row) = ...
                sum(result.numGlobalSwitches);

            %% -------------------------------------------------------
            % Time paths
            %% -------------------------------------------------------

            fitnessPath(row,:) = ...
                result.F(:)';

            riskPath(row,:) = ...
                result.R(:)';

            tradePath(row,:) = ...
                result.totalTrade(:)';

            recoveringLinksPath(row,:) = ...
                result.numRecoveringLinks(:)';

            switchPath(row,:) = ...
                result.numSwitches(:)';

        end

    end

end

%% ------------------------------------------------------------------------
% Main results table
%% ------------------------------------------------------------------------

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        recoveryHorizon, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches);

%% ------------------------------------------------------------------------
% Aggregate by recovery horizon and scenario
%% ------------------------------------------------------------------------

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["recoveryHorizon", ...
         "scenarioID", ...
         "scenarioName"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "finalFitness", ...
            "finalRisk", ...
            "finalTrade", ...
            "finalRecoveringLinks", ...
            "totalSwitches", ...
            "localSwitches", ...
            "globalSwitches" ...
        ]);

%% ------------------------------------------------------------------------
% Paired differences relative to baseline
%% ------------------------------------------------------------------------

differenceRows = [];

for r = 1:nReplications

    for h = 1:nHorizons

        H = ...
            recoveryHorizons(h);

        rowsRH = ...
            summaryTable.replication == r ...
            & summaryTable.recoveryHorizon == H;

        baselineRow = ...
            rowsRH ...
            & summaryTable.scenarioID == "baseline";

        baselineFitness = ...
            summaryTable.finalFitness(baselineRow);

        baselineRisk = ...
            summaryTable.finalRisk(baselineRow);

        baselineTrade = ...
            summaryTable.finalTrade(baselineRow);

        baselineRecovering = ...
            summaryTable.finalRecoveringLinks(baselineRow);

        baselineSwitches = ...
            summaryTable.totalSwitches(baselineRow);

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            scenarioRow = ...
                rowsRH ...
                & summaryTable.scenarioID == scenario.id;

            newRow = ...
                table( ...
                    r, ...
                    seeds(r), ...
                    H, ...
                    string(scenario.id), ...
                    string(scenario.name), ...
                    summaryTable.finalFitness(scenarioRow) ...
                        - baselineFitness, ...
                    summaryTable.finalRisk(scenarioRow) ...
                        - baselineRisk, ...
                    summaryTable.finalTrade(scenarioRow) ...
                        - baselineTrade, ...
                    summaryTable.finalRecoveringLinks(scenarioRow) ...
                        - baselineRecovering, ...
                    summaryTable.totalSwitches(scenarioRow) ...
                        - baselineSwitches, ...
                    'VariableNames', { ...
                        'replication', ...
                        'seed', ...
                        'recovery_horizon', ...
                        'scenario_id', ...
                        'scenario_name', ...
                        'delta_final_fitness_vs_baseline', ...
                        'delta_final_risk_vs_baseline', ...
                        'delta_final_trade_vs_baseline', ...
                        'delta_recovering_links_vs_baseline', ...
                        'delta_total_switches_vs_baseline' ...
                    });

            differenceRows = ...
                [differenceRows; newRow]; %#ok<AGROW>

        end

    end

end

%% ------------------------------------------------------------------------
% Pairwise policy comparisons
%% ------------------------------------------------------------------------

policyIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];

pairwiseRows = [];

for r = 1:nReplications

    for h = 1:nHorizons

        H = ...
            recoveryHorizons(h);

        rowsRH = ...
            summaryTable.replication == r ...
            & summaryTable.recoveryHorizon == H;

        for a = 1:numel(policyIDs)

            for b = (a+1):numel(policyIDs)

                idA = ...
                    policyIDs(a);

                idB = ...
                    policyIDs(b);

                rowA = ...
                    rowsRH ...
                    & summaryTable.scenarioID == idA;

                rowB = ...
                    rowsRH ...
                    & summaryTable.scenarioID == idB;

                newPair = ...
                    table( ...
                        r, ...
                        seeds(r), ...
                        H, ...
                        idA, ...
                        idB, ...
                        summaryTable.finalFitness(rowA) ...
                            - summaryTable.finalFitness(rowB), ...
                        summaryTable.finalRisk(rowA) ...
                            - summaryTable.finalRisk(rowB), ...
                        summaryTable.finalTrade(rowA) ...
                            - summaryTable.finalTrade(rowB), ...
                        summaryTable.totalSwitches(rowA) ...
                            - summaryTable.totalSwitches(rowB), ...
                        'VariableNames', { ...
                            'replication', ...
                            'seed', ...
                            'recovery_horizon', ...
                            'scenario_A', ...
                            'scenario_B', ...
                            'delta_final_fitness_A_minus_B', ...
                            'delta_final_risk_A_minus_B', ...
                            'delta_final_trade_A_minus_B', ...
                            'delta_switches_A_minus_B' ...
                        });

                pairwiseRows = ...
                    [pairwiseRows; newPair]; %#ok<AGROW>

            end

        end

    end

end

%% ------------------------------------------------------------------------
% Identify lowest-risk policy within each network and H
%% ------------------------------------------------------------------------

winnerReplication = ...
    zeros(nReplications * nHorizons,1);

winnerHorizon = ...
    zeros(nReplications * nHorizons,1);

winnerScenario = ...
    strings(nReplications * nHorizons,1);

winnerRisk = ...
    zeros(nReplications * nHorizons,1);

winnerRow = 0;

for r = 1:nReplications

    for h = 1:nHorizons

        H = ...
            recoveryHorizons(h);

        rowsRH = ...
            summaryTable.replication == r ...
            & summaryTable.recoveryHorizon == H ...
            & summaryTable.scenarioID ~= "baseline";

        policyRows = ...
            find(rowsRH);

        risks = ...
            summaryTable.finalRisk(policyRows);

        [minRisk, idx] = ...
            min(risks);

        selectedRow = ...
            policyRows(idx);

        winnerRow = ...
            winnerRow + 1;

        winnerReplication(winnerRow) = ...
            r;

        winnerHorizon(winnerRow) = ...
            H;

        winnerScenario(winnerRow) = ...
            summaryTable.scenarioID(selectedRow);

        winnerRisk(winnerRow) = ...
            minRisk;

    end

end

winnerTable = ...
    table( ...
        winnerReplication, ...
        winnerHorizon, ...
        winnerScenario, ...
        winnerRisk, ...
        'VariableNames', { ...
            'replication', ...
            'recovery_horizon', ...
            'lowest_risk_scenario', ...
            'lowest_final_risk'});

%% ------------------------------------------------------------------------
% Winner frequencies
%% ------------------------------------------------------------------------
winnerFrequency = ...
    groupcounts( ...
        winnerTable, ...
        ["recovery_horizon", ...
         "lowest_risk_scenario"]);

%% ------------------------------------------------------------------------
% Save outputs
%% ------------------------------------------------------------------------

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "pairwiseRows", ...
    "winnerTable", ...
    "winnerFrequency", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "params", ...
    "seeds", ...
    "recoveryHorizons", ...
    "scenarioList", ...
    "-v7.3");

%% Main results

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_summary.csv"));

%% Aggregates

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_aggregate.csv"));

%% Differences versus baseline

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_differences.csv"));

%% Pairwise policy comparisons

writetable( ...
    pairwiseRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_pairwise.csv"));

%% Lowest-risk policy by replication/H

writetable( ...
    winnerTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_winners.csv"));

%% Winner frequencies

writetable( ...
    winnerFrequency, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_recovery_winner_frequency.csv"));

%% ------------------------------------------------------------------------
% Display aggregate output
%% ------------------------------------------------------------------------

fprintf("\n");
fprintf("Joint robustness complete.\n\n");

disp(aggregateTable);

fprintf("\nLowest-risk scenario frequencies:\n\n");

disp(winnerFrequency);

fprintf( ...
    "\nResults saved in:\n%s\n", ...
    resultsDir);