%% ROBUSTNESS: TRADE-RELATIONSHIP RECOVERY HORIZON
% Tests whether the policy-timing result depends on the assumed speed at
% which newly formed trade relationships rebuild toward their pre-switch
% trade volume.
%
% FINAL MODEL LOGIC:
%
%   one model period = one year
%
%   new relationship initial volume:
%
%       W_new,0 = W_old * wHat_new
%
%   surviving replacement relationships recover linearly toward W_old.
%
% The only element varied here is the recovery horizon:
%
%       H = 3 years
%       H = 5 years   [baseline]
%       H = 7 years
%
% No behavioral decision rule is changed.
%
% COMMON RANDOM NUMBERS:
% All policy scenarios within each H specification start from the same
% initial network and stochastic state.

clear;
clc;

%% Paths

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath( ...
    fullfile(projectRoot, "src"));

addpath( ...
    fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "recovery_horizon");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% Load inputs

data = ...
    load_model_data(dataDir);

%% Locked baseline parameters

params.T = 20;

params.p = 0.50;

params.eL = 0.10;

params.eG = 0.20;

params.beta = 4.0;

assert( ...
    params.eG > params.eL, ...
    "Global switching cost eG must exceed local switching cost eL.");

%% Recovery-horizon values

recoveryHorizons = [3 5 7];

%% Initialize one common synthetic network

rng(42, "twister");

initialState = ...
    initialize_network(data);

%% Save stochastic state after initialization

simulationRNG = ...
    rng;

%% Define scenarios

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

nHorizons = ...
    numel(recoveryHorizons);

%% Output storage

allResults = struct();

nRows = ...
    nHorizons * nScenarios;

recoveryHorizonColumn = ...
    zeros(nRows,1);

scenarioID = ...
    strings(nRows,1);

scenarioName = ...
    strings(nRows,1);

finalFitness = ...
    zeros(nRows,1);

finalRisk = ...
    zeros(nRows,1);

finalTrade = ...
    zeros(nRows,1);

finalRecoveringLinks = ...
    zeros(nRows,1);

totalSwitches = ...
    zeros(nRows,1);

localSwitches = ...
    zeros(nRows,1);

globalSwitches = ...
    zeros(nRows,1);

%% Full trajectories

fitnessPath = ...
    zeros(nRows, params.T + 1);

riskPath = ...
    zeros(nRows, params.T + 1);

tradePath = ...
    zeros(nRows, params.T + 1);

recoveringLinksPath = ...
    zeros(nRows, params.T + 1);

switchPath = ...
    zeros(nRows, params.T);

row = 0;

%% Run robustness

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Recovery-Horizon Robustness\n");
fprintf("============================================================\n\n");

for h = 1:nHorizons

    params.recoveryHorizon = ...
        recoveryHorizons(h);

    horizonField = ...
        sprintf( ...
            "H_%d", ...
            params.recoveryHorizon);

    allResults.(horizonField) = ...
        struct();

    fprintf( ...
        "\nRunning recovery horizon H = %d years\n", ...
        params.recoveryHorizon);

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        fprintf( ...
            "  Scenario %d/%d: %s\n", ...
            s, ...
            nScenarios, ...
            scenario.name);

        %% Common random numbers

        rng(simulationRNG);

        %% Run model

        result = ...
            run_model( ...
                initialState, ...
                data, ...
                params, ...
                scenario);

        allResults.(horizonField).(scenario.id) = ...
            result;

        row = ...
            row + 1;

        %% Compact outputs

        recoveryHorizonColumn(row) = ...
            params.recoveryHorizon;

        scenarioID(row) = ...
            scenario.id;

        scenarioName(row) = ...
            scenario.name;

        finalFitness(row) = ...
            result.F(end);

        finalRisk(row) = ...
            result.R(end);

        finalTrade(row) = ...
            result.totalTrade(end);

        finalRecoveringLinks(row) = ...
            result.numRecoveringLinks(end);

        totalSwitches(row) = ...
            sum(result.numSwitches);

        localSwitches(row) = ...
            sum(result.numLocalSwitches);

        globalSwitches(row) = ...
            sum(result.numGlobalSwitches);

        %% Full time paths

        fitnessPath(row,:) = ...
            result.F(:)';

        riskPath(row,:) = ...
            result.R(:)';

        tradePath(row,:) = ...
            result.totalTrade(:)';

        recoveringLinksPath(row,:) = ...
            result.numRecoveringLinks(:)';

        switchPath(row,:) = ...
            result.numSwitches(:)';

    end

end

%% Summary table

summaryTable = ...
    table( ...
        recoveryHorizonColumn, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches, ...
        'VariableNames', { ...
            'recovery_horizon', ...
            'scenario_id', ...
            'scenario_name', ...
            'final_fitness', ...
            'final_risk', ...
            'final_trade', ...
            'final_recovering_links', ...
            'total_switches', ...
            'local_switches', ...
            'global_switches'});

%% Paired differences relative to baseline

differenceRows = [];

for h = 1:nHorizons

    H = ...
        recoveryHorizons(h);

    horizonRows = ...
        summaryTable.recovery_horizon == H;

    baselineRow = ...
        horizonRows ...
        & summaryTable.scenario_id == "baseline";

    baselineFitness = ...
        summaryTable.final_fitness(baselineRow);

    baselineRisk = ...
        summaryTable.final_risk(baselineRow);

    baselineTrade = ...
        summaryTable.final_trade(baselineRow);

    baselineRecovering = ...
        summaryTable.final_recovering_links(baselineRow);

    baselineSwitches = ...
        summaryTable.total_switches(baselineRow);

    for s = 1:nScenarios

        scenario = ...
            scenarioList{s};

        scenarioRow = ...
            horizonRows ...
            & summaryTable.scenario_id == scenario.id;

        newRow = ...
            table( ...
                H, ...
                string(scenario.id), ...
                string(scenario.name), ...
                summaryTable.final_fitness(scenarioRow) ...
                    - baselineFitness, ...
                summaryTable.final_risk(scenarioRow) ...
                    - baselineRisk, ...
                summaryTable.final_trade(scenarioRow) ...
                    - baselineTrade, ...
                summaryTable.final_recovering_links(scenarioRow) ...
                    - baselineRecovering, ...
                summaryTable.total_switches(scenarioRow) ...
                    - baselineSwitches, ...
                'VariableNames', { ...
                    'recovery_horizon', ...
                    'scenario_id', ...
                    'scenario_name', ...
                    'delta_final_fitness_vs_baseline', ...
                    'delta_final_risk_vs_baseline', ...
                    'delta_final_trade_vs_baseline', ...
                    'delta_recovering_links_vs_baseline', ...
                    'delta_total_switches_vs_baseline'});

        differenceRows = ...
            [differenceRows; newRow]; %#ok<AGROW>

    end

end

%% Pairwise policy comparisons

policyIDs = [
    "early_mover"
    "sequential"
    "coordinated"
    "delayed_coordination"
];

pairwiseRows = [];

for h = 1:nHorizons

    H = ...
        recoveryHorizons(h);

    horizonRows = ...
        summaryTable.recovery_horizon == H;

    for a = 1:numel(policyIDs)

        for b = (a+1):numel(policyIDs)

            idA = ...
                policyIDs(a);

            idB = ...
                policyIDs(b);

            rowA = ...
                horizonRows ...
                & summaryTable.scenario_id == idA;

            rowB = ...
                horizonRows ...
                & summaryTable.scenario_id == idB;

            newPair = ...
                table( ...
                    H, ...
                    idA, ...
                    idB, ...
                    summaryTable.final_fitness(rowA) ...
                        - summaryTable.final_fitness(rowB), ...
                    summaryTable.final_risk(rowA) ...
                        - summaryTable.final_risk(rowB), ...
                    summaryTable.final_trade(rowA) ...
                        - summaryTable.final_trade(rowB), ...
                    summaryTable.total_switches(rowA) ...
                        - summaryTable.total_switches(rowB), ...
                    'VariableNames', { ...
                        'recovery_horizon', ...
                        'scenario_A', ...
                        'scenario_B', ...
                        'delta_final_fitness_A_minus_B', ...
                        'delta_final_risk_A_minus_B', ...
                        'delta_final_trade_A_minus_B', ...
                        'delta_switches_A_minus_B'});

            pairwiseRows = ...
                [pairwiseRows; newPair]; %#ok<AGROW>

        end

    end

end

%% Save

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_recovery_horizon_results.mat"), ...
    "allResults", ...
    "summaryTable", ...
    "differenceRows", ...
    "pairwiseRows", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "recoveryHorizons", ...
    "scenarioList", ...
    "simulationRNG", ...
    "-v7.3");

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_recovery_horizon_summary.csv"));

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_recovery_horizon_differences.csv"));

writetable( ...
    pairwiseRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_recovery_horizon_pairwise.csv"));

%% Display

fprintf("\nRecovery-horizon robustness complete.\n\n");

disp(summaryTable);

fprintf( ...
    "\nResults saved in:\n%s\n", ...
    resultsDir);