%% ROBUSTNESS: INITIAL NETWORKS x CHOICE SENSITIVITY beta
%
% Tests whether the timing result depends on softmax choice sensitivity.
%
% Design:
%
%   100 initial networks
%   x beta = [2,4,8]
%   x 5 scenarios
%
%   = 1500 simulations
%
% beta = 4 is the baseline.
%
% Lower beta:
%   more diffuse/stochastic partner choice
%
% Higher beta:
%   greater concentration on high-scoring partners.

clear;
clc;

%% Paths

projectRoot = ...
    fileparts(fileparts(mfilename("fullpath")));

addpath(fullfile(projectRoot, "src"));
addpath(fullfile(projectRoot, "scenarios"));

dataDir = ...
    fullfile(projectRoot, "data");

resultsDir = ...
    fullfile( ...
        projectRoot, ...
        "results", ...
        "robustness", ...
        "networks_beta");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

%% Data

data = ...
    load_model_data(dataDir);

%% Fixed parameters

params.T = 20;

params.p = 0.50;

params.eL = 0.10;

params.eG = 0.20;

params.recoveryHorizon = 5;

assert(params.eG > params.eL);

%% Beta values

betaValues = ...
    [2 4 8];

nBeta = ...
    numel(betaValues);

%% Monte Carlo

nReplications = 100;

seeds = ...
    (1:nReplications)';

%% Scenarios

scenarioList = {
    baseline(data, params.T)
    early_mover(data, params.T)
    sequential(data, params.T)
    coordinated(data, params.T)
    delayed_coordination(data, params.T)
};

nScenarios = ...
    numel(scenarioList);

%% Storage

nRows = ...
    nReplications ...
    * nBeta ...
    * nScenarios;

replication = zeros(nRows,1);
seed = zeros(nRows,1);

betaColumn = zeros(nRows,1);

scenarioID = strings(nRows,1);
scenarioName = strings(nRows,1);

finalFitness = zeros(nRows,1);
finalRisk = zeros(nRows,1);
finalTrade = zeros(nRows,1);
finalRecoveringLinks = zeros(nRows,1);

totalSwitches = zeros(nRows,1);
localSwitches = zeros(nRows,1);
globalSwitches = zeros(nRows,1);

fitnessPath = zeros(nRows, params.T + 1);
riskPath = zeros(nRows, params.T + 1);
tradePath = zeros(nRows, params.T + 1);
recoveringLinksPath = zeros(nRows, params.T + 1);
switchPath = zeros(nRows, params.T);

row = 0;

%% Run

fprintf("\n");
fprintf("============================================================\n");
fprintf(" Initial-Network x Beta Robustness\n");
fprintf("============================================================\n\n");

for r = 1:nReplications

    rng(seeds(r), "twister");

    initialState = ...
        initialize_network(data);

    simulationRNG = ...
        rng;

    fprintf("Replication %d/%d\n", r, nReplications);

    for bb = 1:nBeta

        params.beta = ...
            betaValues(bb);

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            rng(simulationRNG);

            result = ...
                run_model( ...
                    initialState, ...
                    data, ...
                    params, ...
                    scenario);

            row = ...
                row + 1;

            replication(row) = r;
            seed(row) = seeds(r);

            betaColumn(row) = ...
                params.beta;

            scenarioID(row) = ...
                scenario.id;

            scenarioName(row) = ...
                scenario.name;

            finalFitness(row) = ...
                result.F(end);

            finalRisk(row) = ...
                result.R(end);

            finalTrade(row) = ...
                result.totalTrade(end);

            finalRecoveringLinks(row) = ...
                result.numRecoveringLinks(end);

            totalSwitches(row) = ...
                sum(result.numSwitches);

            localSwitches(row) = ...
                sum(result.numLocalSwitches);

            globalSwitches(row) = ...
                sum(result.numGlobalSwitches);

            fitnessPath(row,:) = ...
                result.F(:)';

            riskPath(row,:) = ...
                result.R(:)';

            tradePath(row,:) = ...
                result.totalTrade(:)';

            recoveringLinksPath(row,:) = ...
                result.numRecoveringLinks(:)';

            switchPath(row,:) = ...
                result.numSwitches(:)';

        end

    end

end

%% Checkpoint

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_checkpoint.mat"), ...
    "replication", ...
    "seed", ...
    "betaColumn", ...
    "scenarioID", ...
    "scenarioName", ...
    "finalFitness", ...
    "finalRisk", ...
    "finalTrade", ...
    "finalRecoveringLinks", ...
    "totalSwitches", ...
    "localSwitches", ...
    "globalSwitches", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "betaValues", ...
    "scenarioList", ...
    "-v7.3");

fprintf("\nCheckpoint saved.\n");

%% Summary

summaryTable = ...
    table( ...
        replication, ...
        seed, ...
        betaColumn, ...
        scenarioID, ...
        scenarioName, ...
        finalFitness, ...
        finalRisk, ...
        finalTrade, ...
        finalRecoveringLinks, ...
        totalSwitches, ...
        localSwitches, ...
        globalSwitches, ...
        'VariableNames', { ...
            'replication', ...
            'seed', ...
            'beta', ...
            'scenario_id', ...
            'scenario_name', ...
            'final_fitness', ...
            'final_risk', ...
            'final_trade', ...
            'final_recovering_links', ...
            'total_switches', ...
            'local_switches', ...
            'global_switches'});

aggregateTable = ...
    groupsummary( ...
        summaryTable, ...
        ["beta","scenario_id","scenario_name"], ...
        ["mean","std","median","min","max"], ...
        [ ...
            "final_fitness", ...
            "final_risk", ...
            "final_trade", ...
            "final_recovering_links", ...
            "total_switches", ...
            "local_switches", ...
            "global_switches" ...
        ]);

%% Differences

differenceRows = [];

for r = 1:nReplications

    for bb = 1:nBeta

        betaValue = ...
            betaValues(bb);

        rowsRB = ...
            summaryTable.replication == r ...
            & summaryTable.beta == betaValue;

        baselineRow = ...
            rowsRB ...
            & summaryTable.scenario_id == "baseline";

        baselineFitness = ...
            summaryTable.final_fitness(baselineRow);

        baselineRisk = ...
            summaryTable.final_risk(baselineRow);

        baselineTrade = ...
            summaryTable.final_trade(baselineRow);

        baselineSwitches = ...
            summaryTable.total_switches(baselineRow);

        for s = 1:nScenarios

            scenario = ...
                scenarioList{s};

            scenarioRow = ...
                rowsRB ...
                & summaryTable.scenario_id == scenario.id;

            newRow = ...
                table( ...
                    r, ...
                    seeds(r), ...
                    betaValue, ...
                    string(scenario.id), ...
                    summaryTable.final_fitness(scenarioRow) ...
                        - baselineFitness, ...
                    summaryTable.final_risk(scenarioRow) ...
                        - baselineRisk, ...
                    summaryTable.final_trade(scenarioRow) ...
                        - baselineTrade, ...
                    summaryTable.total_switches(scenarioRow) ...
                        - baselineSwitches, ...
                    'VariableNames', { ...
                        'replication', ...
                        'seed', ...
                        'beta', ...
                        'scenario_id', ...
                        'delta_final_fitness_vs_baseline', ...
                        'delta_final_risk_vs_baseline', ...
                        'delta_final_trade_vs_baseline', ...
                        'delta_total_switches_vs_baseline'});

            differenceRows = ...
                [differenceRows; newRow]; %#ok<AGROW>

        end

    end

end

%% Winners

winnerReplication = ...
    zeros(nReplications*nBeta,1);

winnerBeta = ...
    zeros(nReplications*nBeta,1);

winnerScenario = ...
    strings(nReplications*nBeta,1);

winnerRisk = ...
    zeros(nReplications*nBeta,1);

winnerRow = 0;

for r = 1:nReplications

    for bb = 1:nBeta

        betaValue = ...
            betaValues(bb);

        rowsRB = ...
            summaryTable.replication == r ...
            & summaryTable.beta == betaValue ...
            & summaryTable.scenario_id ~= "baseline";

        policyRows = ...
            find(rowsRB);

        risks = ...
            summaryTable.final_risk(policyRows);

        [minRisk, idx] = ...
            min(risks);

        selectedRow = ...
            policyRows(idx);

        winnerRow = ...
            winnerRow + 1;

        winnerReplication(winnerRow) = r;
        winnerBeta(winnerRow) = betaValue;

        winnerScenario(winnerRow) = ...
            summaryTable.scenario_id(selectedRow);

        winnerRisk(winnerRow) = ...
            minRisk;

    end

end

winnerTable = ...
    table( ...
        winnerReplication, ...
        winnerBeta, ...
        winnerScenario, ...
        winnerRisk, ...
        'VariableNames', { ...
            'replication', ...
            'beta', ...
            'lowest_risk_scenario', ...
            'lowest_final_risk'});

winnerFrequency = ...
    groupcounts( ...
        winnerTable, ...
        ["beta","lowest_risk_scenario"]);

%% Save

save( ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_results.mat"), ...
    "summaryTable", ...
    "aggregateTable", ...
    "differenceRows", ...
    "winnerTable", ...
    "winnerFrequency", ...
    "fitnessPath", ...
    "riskPath", ...
    "tradePath", ...
    "recoveringLinksPath", ...
    "switchPath", ...
    "betaValues", ...
    "scenarioList", ...
    "-v7.3");

writetable( ...
    summaryTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_summary.csv"));

writetable( ...
    aggregateTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_aggregate.csv"));

writetable( ...
    differenceRows, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_differences.csv"));

writetable( ...
    winnerTable, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_winners.csv"));

writetable( ...
    winnerFrequency, ...
    fullfile( ...
        resultsDir, ...
        "robustness_networks_beta_winner_frequency.csv"));

fprintf("\nBeta robustness complete.\n\n");
disp(aggregateTable);
disp(winnerFrequency);

fprintf("\nResults saved in:\n%s\n", resultsDir);